//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assembly
    {
        public int AssemblyID { get; set; }
        public int PackageID { get; set; }
        public string AssemblyName { get; set; }
        public string Version { get; set; }
    
        public virtual Package Package { get; set; }
    }
}
