//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_ProductsLITypesTexts
    {
        public int ProductLITypeTextID { get; set; }
        public int ProductID { get; set; }
        public int TypeTextID { get; set; }
        public Nullable<int> ViewOrder { get; set; }
    
        public virtual CAT_TypesTexts CAT_TypesTexts { get; set; }
    }
}
