//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_Threads
    {
        public CAT_Threads()
        {
            this.CAT_Posts = new HashSet<CAT_Posts>();
        }
    
        public int ThreadID { get; set; }
        public Nullable<int> LastPostedPostID { get; set; }
        public int NotifiedUserID { get; set; }
        public int PortalID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Subject { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string ProfileProperties { get; set; }
    
        public virtual ICollection<CAT_Posts> CAT_Posts { get; set; }
        public virtual User User { get; set; }
    }
}
