//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_VendorPermission
    {
        public int VendorPermissionID { get; set; }
        public int PortalID { get; set; }
        public int PermissionID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public int MaxCount { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
    
        public virtual CAT_StorePermission CAT_StorePermission { get; set; }
        public virtual Portal Portal { get; set; }
        public virtual User User { get; set; }
    }
}
