//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_AdvCatPermission
    {
        public int AdvCatPermissionID { get; set; }
        public int AdvCatID { get; set; }
        public int PermissionID { get; set; }
        public int RoleID { get; set; }
        public bool AllowAccess { get; set; }
    
        public virtual CAT_AdvCats CAT_AdvCats { get; set; }
        public virtual CAT_StorePermission CAT_StorePermission { get; set; }
    }
}
