//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_Settings
    {
        public int SettingID { get; set; }
        public int PortalID { get; set; }
        public int StoreOwnerUserID { get; set; }
        public Nullable<int> PostItems { get; set; }
        public Nullable<int> StorePaymentTypes { get; set; }
        public int StoreCCTypes { get; set; }
        public string CCLogin { get; set; }
        public string CCTransactionKey { get; set; }
        public string CCPassword { get; set; }
        public string CCCryptoPassword { get; set; }
        public string CCMerchantHash { get; set; }
        public bool StorePriceType { get; set; }
        public Nullable<decimal> StoreTax { get; set; }
        public string PayPalID { get; set; }
        public string PayPalCartName { get; set; }
        public Nullable<int> StoreCurrencyid { get; set; }
        public int CCPaymentProcessorID { get; set; }
        public Nullable<int> PayPalReturnTabID { get; set; }
        public string PayPalButtonURL { get; set; }
        public string LicenceKey { get; set; }
        public string StoreEmail { get; set; }
        public string SMTPUserName { get; set; }
        public string SMTPPassword { get; set; }
        public int SMTPPort { get; set; }
        public string SMTPServer { get; set; }
        public bool ShowNodeImages { get; set; }
        public bool ShowPriceHistory { get; set; }
        public bool ShowPriceAgent { get; set; }
        public bool StockControl { get; set; }
        public string StockImage1 { get; set; }
        public string StockImage2 { get; set; }
        public string StockImage3 { get; set; }
        public string StockImage4 { get; set; }
        public Nullable<int> StockLimit1 { get; set; }
        public Nullable<int> StockLimit2 { get; set; }
        public Nullable<int> StockLimit3 { get; set; }
        public string TopTemplate { get; set; }
        public string BottomTemplate { get; set; }
        public string TitleSide { get; set; }
        public decimal FreightFlatRate { get; set; }
        public decimal FreightCostsForKg { get; set; }
        public string FreightCostsType { get; set; }
        public decimal FreightCODCosts { get; set; }
        public decimal FreightInsurance { get; set; }
        public Nullable<decimal> woFreightFromLimit { get; set; }
        public bool StockControlType { get; set; }
        public decimal OrderUnderLimit { get; set; }
        public bool ShowOnlyIfStock { get; set; }
        public string PriceOfferDescription { get; set; }
        public bool PublicAttributes { get; set; }
        public int PagingPageSize { get; set; }
        public bool DoNotShowTerms { get; set; }
        public bool EnableShipping { get; set; }
        public bool FolderLinks { get; set; }
        public int RewardPeriod { get; set; }
        public decimal ReferrerCommission { get; set; }
        public decimal VendorCommission { get; set; }
        public string Skin { get; set; }
        public bool SaveCCData { get; set; }
        public string OrigCountry { get; set; }
        public string OrigStateProvince { get; set; }
        public string OrigZipPostal { get; set; }
        public string UPSUserName { get; set; }
        public string UPSPassword { get; set; }
        public string UPSAccessLicense { get; set; }
        public string USPSUserName { get; set; }
        public string USPSPassword { get; set; }
        public string CanPostMerchCPCID { get; set; }
        public int ShippingCompanies { get; set; }
        public string LimitRates { get; set; }
        public string ExcludeRates { get; set; }
        public string UPSPickup { get; set; }
        public string UPSPack { get; set; }
        public string DHLServices { get; set; }
        public string FedExPack { get; set; }
        public bool FedExGround { get; set; }
        public string RateBackup { get; set; }
        public string RateFailover { get; set; }
        public string AdjustRate { get; set; }
        public string WeightUnit { get; set; }
        public bool EnableRequQuote { get; set; }
        public string ImportFields { get; set; }
        public string ImportFile { get; set; }
        public bool SyncItems { get; set; }
        public bool CurrencyConverter { get; set; }
        public string InvoiceCreationType { get; set; }
        public string CCTransactionType { get; set; }
        public int StartPaymentTypes { get; set; }
        public string CCAdditionalParameters { get; set; }
        public string EmailTemplatePackage { get; set; }
        public string OptionsTextFilter { get; set; }
        public bool InventoryCheck { get; set; }
        public string WatermarkParams { get; set; }
        public string FreightInsuranceBasis { get; set; }
        public bool CCTestMode { get; set; }
        public bool USPSTestMode { get; set; }
        public string EmailEncoding { get; set; }
        public string CCBlockList { get; set; }
        public string IPBlockList { get; set; }
        public string FedExAccountNumber { get; set; }
        public string FedExPickup { get; set; }
        public string FedExURL { get; set; }
        public int NumberDecimalDigits { get; set; }
        public string UPSAccountNumber { get; set; }
        public bool UPSNegotiatedRates { get; set; }
        public string PayPalURL { get; set; }
        public string PayPalSandboxURL { get; set; }
        public int PayPalCurrencyID { get; set; }
        public string PayPalShippingAddress { get; set; }
        public bool PayPalPassingIndividualItems { get; set; }
        public string UnitOfMeasurement { get; set; }
        public bool EmailSender1 { get; set; }
        public bool EnableAJAX { get; set; }
        public int PointsConversionRate { get; set; }
        public string OrigCity { get; set; }
        public string AffiliateCode { get; set; }
        public string AnalyticsCode { get; set; }
        public string FraktguideUserCode { get; set; }
        public string FraktguideProductIDs { get; set; }
        public string BidIncrementFormula { get; set; }
        public bool StorePriceInputType { get; set; }
        public string CCUserName { get; set; }
        public int RoleExpiryDateOffset { get; set; }
        public string USPSServices { get; set; }
        public string OrigStreet { get; set; }
        public Nullable<bool> FedExNegotiatedRates { get; set; }
    
        public virtual Portal Portal { get; set; }
    }
}
