//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_ProductImages
    {
        public int ImageID { get; set; }
        public int ProductID { get; set; }
        public string ImageURL { get; set; }
        public string ImageFile { get; set; }
        public string Description { get; set; }
        public string ImageType { get; set; }
        public Nullable<int> ViewOrder { get; set; }
    
        public virtual CAT_Products CAT_Products { get; set; }
    }
}
