//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_TypesSpecs
    {
        public CAT_TypesSpecs()
        {
            this.CAT_ProductsTypesSpecs = new HashSet<CAT_ProductsTypesSpecs>();
        }
    
        public int TypeSpecID { get; set; }
        public int ProductTypeID { get; set; }
        public int SpecificationID { get; set; }
    
        public virtual ICollection<CAT_ProductsTypesSpecs> CAT_ProductsTypesSpecs { get; set; }
        public virtual CAT_ProductTypes CAT_ProductTypes { get; set; }
    }
}
