//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_Products
    {
        public CAT_Products()
        {
            this.CAT_AdvCatProducts = new HashSet<CAT_AdvCatProducts>();
            this.CAT_OrderDetails = new HashSet<CAT_OrderDetails>();
            this.CAT_Periods = new HashSet<CAT_Periods>();
            this.CAT_PriceAgent = new HashSet<CAT_PriceAgent>();
            this.CAT_PriceHistory = new HashSet<CAT_PriceHistory>();
            this.CAT_ProductFiles = new HashSet<CAT_ProductFiles>();
            this.CAT_ProductImages = new HashSet<CAT_ProductImages>();
            this.CAT_ProductPermission = new HashSet<CAT_ProductPermission>();
            this.CAT_ProductsOptions = new HashSet<CAT_ProductsOptions>();
            this.CAT_ProductsSlots = new HashSet<CAT_ProductsSlots>();
            this.CAT_ProductsZonesTax = new HashSet<CAT_ProductsZonesTax>();
            this.CAT_RelatedProducts = new HashSet<CAT_RelatedProducts>();
            this.CAT_Reviews = new HashSet<CAT_Reviews>();
            this.CAT_ShoppingCart = new HashSet<CAT_ShoppingCart>();
            this.TAA_ProductSizes = new HashSet<TAA_ProductSizes>();
            this.TAA_ShoppingCart = new HashSet<TAA_ShoppingCart>();
        }
    
        public int ProductID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Category2ID { get; set; }
        public string Category3 { get; set; }
        public string ProductName { get; set; }
        public string ProductNumber { get; set; }
        public string EAN { get; set; }
        public string ISBN { get; set; }
        public string Free1 { get; set; }
        public string Free2 { get; set; }
        public string Free3 { get; set; }
        public string KeyWords { get; set; }
        public string ProductImage { get; set; }
        public decimal UnitCost { get; set; }
        public Nullable<decimal> UnitCost2 { get; set; }
        public Nullable<decimal> UnitCost3 { get; set; }
        public Nullable<decimal> UnitCost4 { get; set; }
        public Nullable<decimal> UnitCost5 { get; set; }
        public Nullable<decimal> UnitCost6 { get; set; }
        public string Description { get; set; }
        public string DescriptionHTML { get; set; }
        public string URL { get; set; }
        public Nullable<int> Stock { get; set; }
        public string OrderQuant { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> FreightCosts1 { get; set; }
        public Nullable<decimal> FreightCosts2 { get; set; }
        public bool Featured { get; set; }
        public decimal SalePrice { get; set; }
        public Nullable<System.DateTime> SaleStart { get; set; }
        public Nullable<System.DateTime> SaleEnd { get; set; }
        public Nullable<bool> DownLoad { get; set; }
        public string ZIPPassWord { get; set; }
        public string DownLoadFile { get; set; }
        public Nullable<bool> Archive { get; set; }
        public int CreatedByUser { get; set; }
        public int BulkPriceLimit1 { get; set; }
        public int BulkPriceLimit2 { get; set; }
        public int BulkPriceLimit3 { get; set; }
        public int BulkPriceLimit4 { get; set; }
        public int BulkPriceLimit5 { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> SubscriptionPeriod { get; set; }
        public Nullable<bool> RecurringBilling { get; set; }
        public Nullable<bool> TaxExempt { get; set; }
        public Nullable<bool> ShipExempt { get; set; }
        public decimal InsuredValue { get; set; }
        public Nullable<System.DateTime> PublicationStart { get; set; }
        public Nullable<System.DateTime> PublicationEnd { get; set; }
        public string Status { get; set; }
        public bool DonationItem { get; set; }
        public bool PayPalSubscription { get; set; }
        public bool UseRoleFees { get; set; }
        public decimal ProductCost { get; set; }
        public string RoleExpiryType { get; set; }
        public string ItemDeliveryType { get; set; }
        public int ReorderPoint { get; set; }
        public string OrderQuantValidExpr { get; set; }
        public string ShippingAddress { get; set; }
        public Nullable<int> OrigProductID { get; set; }
        public bool AuctionFinished { get; set; }
        public Nullable<decimal> StartingPrice { get; set; }
        public Nullable<decimal> ReservePrice { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public string TaxCode { get; set; }
        public Nullable<decimal> MaxWeight { get; set; }
        public Nullable<int> TotalPeriods { get; set; }
        public Nullable<bool> NonStockItem { get; set; }
        public Nullable<int> StockedColorID { get; set; }
        public Nullable<int> StockedColorID2 { get; set; }
        public Nullable<int> StockedColorID3 { get; set; }
        public Nullable<int> StockedColorID4 { get; set; }
        public Nullable<int> StockedColorID5 { get; set; }
        public Nullable<int> StockedColorID6 { get; set; }
        public Nullable<decimal> DealerTier1Price { get; set; }
        public Nullable<decimal> DealerTier2Price { get; set; }
        public Nullable<decimal> DealerTier3Price { get; set; }
        public Nullable<decimal> DealerTier4Price { get; set; }
        public Nullable<decimal> ConsumerTier1Price { get; set; }
        public Nullable<decimal> ConsumerTier2Price { get; set; }
        public Nullable<decimal> ConsumerTier3Price { get; set; }
        public Nullable<decimal> ConsumerTier4Price { get; set; }
        public string DiscountClass { get; set; }
        public Nullable<int> DiscountClassID { get; set; }
        public Nullable<int> CMSProductID { get; set; }
        public Nullable<int> TAASportID { get; set; }
        public string CMSProductDesign { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual ICollection<CAT_AdvCatProducts> CAT_AdvCatProducts { get; set; }
        public virtual CAT_Categories CAT_Categories { get; set; }
        public virtual ICollection<CAT_OrderDetails> CAT_OrderDetails { get; set; }
        public virtual ICollection<CAT_Periods> CAT_Periods { get; set; }
        public virtual ICollection<CAT_PriceAgent> CAT_PriceAgent { get; set; }
        public virtual ICollection<CAT_PriceHistory> CAT_PriceHistory { get; set; }
        public virtual ICollection<CAT_ProductFiles> CAT_ProductFiles { get; set; }
        public virtual ICollection<CAT_ProductImages> CAT_ProductImages { get; set; }
        public virtual ICollection<CAT_ProductPermission> CAT_ProductPermission { get; set; }
        public virtual ICollection<CAT_ProductsOptions> CAT_ProductsOptions { get; set; }
        public virtual ICollection<CAT_ProductsSlots> CAT_ProductsSlots { get; set; }
        public virtual ICollection<CAT_ProductsZonesTax> CAT_ProductsZonesTax { get; set; }
        public virtual ICollection<CAT_RelatedProducts> CAT_RelatedProducts { get; set; }
        public virtual ICollection<CAT_Reviews> CAT_Reviews { get; set; }
        public virtual ICollection<CAT_ShoppingCart> CAT_ShoppingCart { get; set; }
        public virtual ICollection<TAA_ProductSizes> TAA_ProductSizes { get; set; }
        public virtual ICollection<TAA_ShoppingCart> TAA_ShoppingCart { get; set; }
    }
}
