//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_Checkout
    {
        public int CheckoutID { get; set; }
        public string CartID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Message { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public string ShippingCompany { get; set; }
        public string Rate { get; set; }
        public Nullable<decimal> ShippingCharge { get; set; }
        public Nullable<int> ShipToID { get; set; }
        public string TaxRateName { get; set; }
        public Nullable<System.DateTime> DespatchDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> PickUpDate { get; set; }
        public Nullable<int> ShippingRateID { get; set; }
        public Nullable<decimal> ShipTax { get; set; }
        public Nullable<decimal> ShipTax2 { get; set; }
    }
}
