//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_Bids
    {
        public int BidID { get; set; }
        public Nullable<int> PortalID { get; set; }
        public Nullable<int> BidderUserID { get; set; }
        public string BidderUserName { get; set; }
        public Nullable<int> AuctionID { get; set; }
        public Nullable<decimal> BidAmount { get; set; }
        public Nullable<System.DateTime> BidTime { get; set; }
        public Nullable<bool> AutomaticBid_ { get; set; }
        public Nullable<bool> WinningBid { get; set; }
    }
}
