//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_SlotsProductTypes
    {
        public int SlotProductTypeID { get; set; }
        public int SlotID { get; set; }
        public int ProductTypeID { get; set; }
    
        public virtual CAT_ProductTypes CAT_ProductTypes { get; set; }
    }
}
