//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_AdvCats
    {
        public CAT_AdvCats()
        {
            this.CAT_AdvCatPermission = new HashSet<CAT_AdvCatPermission>();
            this.CAT_AdvCatProducts = new HashSet<CAT_AdvCatProducts>();
            this.CAT_AdvCats1 = new HashSet<CAT_AdvCats>();
        }
    
        public int AdvCatID { get; set; }
        public int AdvCatOrder { get; set; }
        public Nullable<int> PortalID { get; set; }
        public string AdvCatName { get; set; }
        public bool IsVisible { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool DisableLink { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string KeyWords { get; set; }
        public bool IsDeleted { get; set; }
        public string IconFile { get; set; }
        public int Level { get; set; }
        public string AdvCatImportID { get; set; }
    
        public virtual ICollection<CAT_AdvCatPermission> CAT_AdvCatPermission { get; set; }
        public virtual ICollection<CAT_AdvCatProducts> CAT_AdvCatProducts { get; set; }
        public virtual ICollection<CAT_AdvCats> CAT_AdvCats1 { get; set; }
        public virtual CAT_AdvCats CAT_AdvCats2 { get; set; }
        public virtual Portal Portal { get; set; }
    }
}
