//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_Slots
    {
        public CAT_Slots()
        {
            this.CAT_ProductsSlots = new HashSet<CAT_ProductsSlots>();
        }
    
        public int SlotID { get; set; }
        public int PortalID { get; set; }
        public int CreatedByUser { get; set; }
        public string SlotName { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string SlotImage { get; set; }
        public Nullable<int> Preselection { get; set; }
        public string Status { get; set; }
        public int PreselQuant { get; set; }
    
        public virtual ICollection<CAT_ProductsSlots> CAT_ProductsSlots { get; set; }
        public virtual Portal Portal { get; set; }
    }
}
