//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_StorePermission
    {
        public CAT_StorePermission()
        {
            this.CAT_AdvCatPermission = new HashSet<CAT_AdvCatPermission>();
            this.CAT_PaymentMethodPermission = new HashSet<CAT_PaymentMethodPermission>();
            this.CAT_ProductPermission = new HashSet<CAT_ProductPermission>();
            this.CAT_VendorPermission = new HashSet<CAT_VendorPermission>();
        }
    
        public int PermissionID { get; set; }
        public string PermissionCode { get; set; }
        public int ModuleDefID { get; set; }
        public string PermissionKey { get; set; }
        public string PermissionName { get; set; }
        public int ViewOrder { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
    
        public virtual ICollection<CAT_AdvCatPermission> CAT_AdvCatPermission { get; set; }
        public virtual ICollection<CAT_PaymentMethodPermission> CAT_PaymentMethodPermission { get; set; }
        public virtual ICollection<CAT_ProductPermission> CAT_ProductPermission { get; set; }
        public virtual ICollection<CAT_VendorPermission> CAT_VendorPermission { get; set; }
    }
}
