//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_ProdOptionsSelections
    {
        public string POSelID { get; set; }
        public Nullable<int> POSelStock { get; set; }
        public string POSelImage { get; set; }
        public string POSelSKU { get; set; }
        public string Formula { get; set; }
    }
}
