//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_PaymentMethods
    {
        public CAT_PaymentMethods()
        {
            this.CAT_PaymentMethodPermission = new HashSet<CAT_PaymentMethodPermission>();
        }
    
        public int PaymentMethodID { get; set; }
        public Nullable<int> PortalID { get; set; }
        public Nullable<int> CreatedByUser { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Countries { get; set; }
        public string Roles { get; set; }
        public string Formula { get; set; }
        public Nullable<int> CCPaymentProcessorID { get; set; }
        public string CCTransactionType { get; set; }
        public Nullable<int> ViewOrder { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public string CCBrand { get; set; }
        public Nullable<int> StoreCCTypes { get; set; }
        public string CCLogin { get; set; }
        public string CCTransactionKey { get; set; }
        public string CCUserName { get; set; }
        public string CCPassword { get; set; }
        public string CCMerchantHash { get; set; }
        public string CCAdditionalParameters { get; set; }
        public Nullable<bool> CCTestMode { get; set; }
        public Nullable<bool> SaveCCData { get; set; }
        public string PayPalID { get; set; }
        public Nullable<int> PayPalReturnTabID { get; set; }
        public string PayPalCartName { get; set; }
        public string PayPalButtonURL { get; set; }
        public string PayPalURL { get; set; }
        public string PayPalSandboxURL { get; set; }
        public Nullable<int> PayPalCurrencyID { get; set; }
        public string PayPalShippingAddress { get; set; }
        public Nullable<bool> PayPalPassingIndividualItems { get; set; }
        public string LogoImage { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> PMCategoryID { get; set; }
        public string Formula2 { get; set; }
        public string ProfileProperties { get; set; }
        public Nullable<decimal> TransSuccEmailMinTransAmt { get; set; }
        public string TransSuccEmails { get; set; }
        public string TransSuccEmailSubjTmpl { get; set; }
        public string TransSuccEmailMsgTmpl { get; set; }
        public string TransFailEmails { get; set; }
        public string TransFailEmailSubjTmpl { get; set; }
        public string TransFailEmailMsgTmpl { get; set; }
    
        public virtual ICollection<CAT_PaymentMethodPermission> CAT_PaymentMethodPermission { get; set; }
    }
}
