//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_Referrals
    {
        public int ReferralID { get; set; }
        public int ReferrerUserID { get; set; }
        public int UserID { get; set; }
        public string URLReferrer { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> RewardExpiryDate { get; set; }
        public Nullable<bool> Enabled { get; set; }
    
        public virtual User User { get; set; }
    }
}
