//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_Options
    {
        public CAT_Options()
        {
            this.CAT_ProductsOptions = new HashSet<CAT_ProductsOptions>();
        }
    
        public int OptionID { get; set; }
        public int PortalID { get; set; }
        public int CreatedByUser { get; set; }
        public string OptionName { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Selections { get; set; }
        public string OptionImage { get; set; }
        public string Preselection { get; set; }
        public string Status { get; set; }
        public Nullable<int> RepeatCol { get; set; }
        public string ControlType { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Columns { get; set; }
        public Nullable<int> Rows { get; set; }
        public string SpellCheck { get; set; }
        public string ControlProperties { get; set; }
        public Nullable<bool> AddToPOSelID { get; set; }
    
        public virtual Portal Portal { get; set; }
        public virtual ICollection<CAT_ProductsOptions> CAT_ProductsOptions { get; set; }
    }
}
