//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_Feedbacks
    {
        public CAT_Feedbacks()
        {
            this.CAT_Comments = new HashSet<CAT_Comments>();
        }
    
        public int FeedBackID { get; set; }
        public int UserID { get; set; }
        public string FromUserStatus { get; set; }
        public int PortalID { get; set; }
        public int ItemID { get; set; }
        public int RecordID { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<bool> Approved { get; set; }
    
        public virtual ICollection<CAT_Comments> CAT_Comments { get; set; }
        public virtual User User { get; set; }
    }
}
