//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_ListItemTexts
    {
        public int ListItemTextID { get; set; }
        public int PortalID { get; set; }
        public int CreatedByUser { get; set; }
        public string ListItemTextDescr { get; set; }
    
        public virtual Portal Portal { get; set; }
    }
}
