//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_OrderDetails
    {
        public int OrderDetailsID { get; set; }
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public int QuantityRemaining { get; set; }
        public decimal UnitCost { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> InvoiceShipCosts { get; set; }
        public Nullable<int> CreditNoteNumber { get; set; }
        public Nullable<System.DateTime> CreditNoteDate { get; set; }
        public Nullable<decimal> CreditNoteShipCosts { get; set; }
        public string Options { get; set; }
        public Nullable<System.DateTime> AllocDate { get; set; }
        public Nullable<System.DateTime> SubscrExpiryDate { get; set; }
        public int RecordID { get; set; }
        public Nullable<int> BaseRecID { get; set; }
        public Nullable<int> ProductSlotID { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public decimal ReferrerCommission { get; set; }
        public decimal VendorCommission { get; set; }
        public string ShippingCompany { get; set; }
        public string TrackingNumber { get; set; }
        public int DeliveredUnits { get; set; }
        public string SKU { get; set; }
        public decimal ProductCost { get; set; }
        public int BillingPeriod { get; set; }
        public decimal Tax2 { get; set; }
        public Nullable<int> CouponCodeID { get; set; }
        public Nullable<int> CartPriceRuleID { get; set; }
        public Nullable<decimal> LoyaltyDiscount { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public Nullable<int> PeriodsRemaining { get; set; }
    
        public virtual CAT_Orders CAT_Orders { get; set; }
        public virtual CAT_Products CAT_Products { get; set; }
    }
}
