//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_Organization
    {
        public int UserID { get; set; }
        public string CustomerNumber { get; set; }
        public string Company { get; set; }
        public string TaxNumber { get; set; }
        public string TaxIdentNumber { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> PaymentTypes { get; set; }
        public string AccountType { get; set; }
        public string Account { get; set; }
        public string BankName { get; set; }
        public string SortCode { get; set; }
        public string BankAddress { get; set; }
        public string AccountNumber { get; set; }
        public string AccountOwnerName { get; set; }
        public string IBAN { get; set; }
        public string BIC { get; set; }
        public bool EmailNotifications { get; set; }
        public string Department { get; set; }
        public string LogoImage { get; set; }
        public Nullable<int> AccountStatus { get; set; }
        public string StatusNotes { get; set; }
        public Nullable<int> HomePage { get; set; }
        public string Classification { get; set; }
    
        public virtual User User { get; set; }
    }
}
