//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_ShippingRates
    {
        public int ShippingRateID { get; set; }
        public string Company { get; set; }
        public string RateName { get; set; }
        public string Formula { get; set; }
        public string Country { get; set; }
        public string StateProvince { get; set; }
        public Nullable<decimal> Minimum { get; set; }
        public string AdjustRate { get; set; }
        public string ShipTime { get; set; }
        public bool Visible { get; set; }
        public bool Active { get; set; }
        public int PortalID { get; set; }
        public string ZipPostal { get; set; }
        public Nullable<int> CreatedByUser { get; set; }
        public string ShipperEmailAddress { get; set; }
        public string ShipperEmailSubjectTemplate { get; set; }
        public string ShipperEmailMessageTemplate { get; set; }
        public string ShipperEmailSendType { get; set; }
    }
}
