//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_ListItemTypes
    {
        public CAT_ListItemTypes()
        {
            this.CAT_TypesTexts = new HashSet<CAT_TypesTexts>();
        }
    
        public int ListItemTypeID { get; set; }
        public int PortalID { get; set; }
        public int CreatedByUser { get; set; }
        public string ListItemTypeName { get; set; }
        public string CategoryIDs { get; set; }
    
        public virtual Portal Portal { get; set; }
        public virtual ICollection<CAT_TypesTexts> CAT_TypesTexts { get; set; }
    }
}
