//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_ProductsTypesSpecs
    {
        public int ProductTypeSpecID { get; set; }
        public int ProductID { get; set; }
        public int TypeSpecID { get; set; }
        public string KindOfProductTypeSpec { get; set; }
    
        public virtual CAT_TypesSpecs CAT_TypesSpecs { get; set; }
    }
}
