//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_Categories
    {
        public CAT_Categories()
        {
            this.CAT_Products = new HashSet<CAT_Products>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public int PortalID { get; set; }
        public string CategoryImportID { get; set; }
        public string CategoryFolderImage { get; set; }
        public string CategoryOpenFolderImage { get; set; }
        public string CategoryPageImage { get; set; }
        public Nullable<int> CreatedByUser { get; set; }
    
        public virtual ICollection<CAT_Products> CAT_Products { get; set; }
    }
}
