//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_ProductsOptions
    {
        public int ProductOptionID { get; set; }
        public int ProductID { get; set; }
        public int OptionID { get; set; }
        public Nullable<int> ViewOrder { get; set; }
    
        public virtual CAT_Options CAT_Options { get; set; }
        public virtual CAT_Products CAT_Products { get; set; }
    }
}
