//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentItem
    {
        public ContentItem()
        {
            this.ContentItems_MetaData = new HashSet<ContentItems_MetaData>();
            this.ContentItems_Tags = new HashSet<ContentItems_Tags>();
            this.Modules = new HashSet<Module>();
            this.Tabs = new HashSet<Tab>();
        }
    
        public int ContentItemID { get; set; }
        public string Content { get; set; }
        public int ContentTypeID { get; set; }
        public int TabID { get; set; }
        public int ModuleID { get; set; }
        public string ContentKey { get; set; }
        public bool Indexed { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
    
        public virtual ContentType ContentType { get; set; }
        public virtual ICollection<ContentItems_MetaData> ContentItems_MetaData { get; set; }
        public virtual ICollection<ContentItems_Tags> ContentItems_Tags { get; set; }
        public virtual ICollection<Module> Modules { get; set; }
        public virtual ICollection<Tab> Tabs { get; set; }
    }
}
