//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentItems_MetaData
    {
        public int ContentItemMetaDataID { get; set; }
        public int ContentItemID { get; set; }
        public int MetaDataID { get; set; }
        public string MetaDataValue { get; set; }
    
        public virtual ContentItem ContentItem { get; set; }
        public virtual MetaData MetaData { get; set; }
    }
}
