//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard_Controls
    {
        public int DashboardControlID { get; set; }
        public string DashboardControlKey { get; set; }
        public bool IsEnabled { get; set; }
        public string DashboardControlSrc { get; set; }
        public string DashboardControlLocalResources { get; set; }
        public string ControllerClass { get; set; }
        public int ViewOrder { get; set; }
        public int PackageID { get; set; }
    
        public virtual Package Package { get; set; }
    }
}
