//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesktopModule
    {
        public DesktopModule()
        {
            this.ModuleDefinitions = new HashSet<ModuleDefinition>();
            this.PortalDesktopModules = new HashSet<PortalDesktopModule>();
        }
    
        public int DesktopModuleID { get; set; }
        public string FriendlyName { get; set; }
        public string Description { get; set; }
        public string Version { get; set; }
        public bool IsPremium { get; set; }
        public bool IsAdmin { get; set; }
        public string BusinessControllerClass { get; set; }
        public string FolderName { get; set; }
        public string ModuleName { get; set; }
        public int SupportedFeatures { get; set; }
        public string CompatibleVersions { get; set; }
        public string Dependencies { get; set; }
        public string Permissions { get; set; }
        public int PackageID { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public int ContentItemId { get; set; }
    
        public virtual Package Package { get; set; }
        public virtual ICollection<ModuleDefinition> ModuleDefinitions { get; set; }
        public virtual ICollection<PortalDesktopModule> PortalDesktopModules { get; set; }
    }
}
