//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLogType
    {
        public EventLogType()
        {
            this.EventLogs = new HashSet<EventLog>();
            this.EventLogConfigs = new HashSet<EventLogConfig>();
        }
    
        public string LogTypeKey { get; set; }
        public string LogTypeFriendlyName { get; set; }
        public string LogTypeDescription { get; set; }
        public string LogTypeOwner { get; set; }
        public string LogTypeCSSClass { get; set; }
    
        public virtual ICollection<EventLog> EventLogs { get; set; }
        public virtual ICollection<EventLogConfig> EventLogConfigs { get; set; }
    }
}
