//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLogConfig
    {
        public EventLogConfig()
        {
            this.EventLogs = new HashSet<EventLog>();
        }
    
        public int ID { get; set; }
        public string LogTypeKey { get; set; }
        public Nullable<int> LogTypePortalID { get; set; }
        public bool LoggingIsActive { get; set; }
        public int KeepMostRecent { get; set; }
        public bool EmailNotificationIsActive { get; set; }
        public Nullable<int> NotificationThreshold { get; set; }
        public Nullable<int> NotificationThresholdTime { get; set; }
        public Nullable<int> NotificationThresholdTimeType { get; set; }
        public string MailFromAddress { get; set; }
        public string MailToAddress { get; set; }
    
        public virtual ICollection<EventLog> EventLogs { get; set; }
        public virtual EventLogType EventLogType { get; set; }
    }
}
