//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ
    {
        public int ItemID { get; set; }
        public int ModuleID { get; set; }
        public string CreatedByUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public System.DateTime DateModified { get; set; }
        public int ViewCount { get; set; }
        public int ViewOrder { get; set; }
        public bool FaqHide { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
    
        public virtual Module Module { get; set; }
    }
}
