//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQsCategory
    {
        public int FaqCategoryId { get; set; }
        public int ModuleId { get; set; }
        public string FaqCategoryName { get; set; }
        public string FaqCategoryDescription { get; set; }
        public Nullable<int> FaqCategoryParentId { get; set; }
        public int ViewOrder { get; set; }
    }
}
