//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flyer_Flyer
    {
        public int FlyerID { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public Nullable<int> LogoID { get; set; }
        public Nullable<int> PromoBannerID { get; set; }
        public Nullable<int> MessageID { get; set; }
        public Nullable<int> RecommendationID { get; set; }
        public Nullable<int> HeaderImgID { get; set; }
    
        public virtual Flyer_HeaderImage Flyer_HeaderImage { get; set; }
        public virtual Flyer_Player Flyer_Player { get; set; }
        public virtual Flyer_Rcommendation Flyer_Rcommendation { get; set; }
        public virtual Flyer_Template Flyer_Template { get; set; }
    }
}
