//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flyer_Template
    {
        public Flyer_Template()
        {
            this.Flyer_Flyer = new HashSet<Flyer_Flyer>();
            this.Flyer_Template_Preference = new HashSet<Flyer_Template_Preference>();
            this.Flyer_TemplateRegions = new HashSet<Flyer_TemplateRegions>();
        }
    
        public int TemplateID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> IsinUse { get; set; }
        public Nullable<int> FileID { get; set; }
        public string FileName { get; set; }
        public string FileLocation { get; set; }
        public string TemplateName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<System.DateTime> ActiviatedDate { get; set; }
        public Nullable<System.DateTime> DeActivatedDate { get; set; }
        public Nullable<bool> IsTeamworkAvailable { get; set; }
        public Nullable<bool> IsDealersAvailable { get; set; }
        public Nullable<bool> IsEndUsersAvailable { get; set; }
    
        public virtual ICollection<Flyer_Flyer> Flyer_Flyer { get; set; }
        public virtual Flyer_TemplateType Flyer_TemplateType { get; set; }
        public virtual ICollection<Flyer_Template_Preference> Flyer_Template_Preference { get; set; }
        public virtual ICollection<Flyer_TemplateRegions> Flyer_TemplateRegions { get; set; }
    }
}
