//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flyer_Login
    {
        public int LoginID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string OldPassword { get; set; }
        public string PasswordHint { get; set; }
        public string PasswordHintQuestion { get; set; }
    
        public virtual Flyer_User Flyer_User { get; set; }
    }
}
