//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flyer_HeaderImage
    {
        public Flyer_HeaderImage()
        {
            this.Flyer_Flyer = new HashSet<Flyer_Flyer>();
        }
    
        public int HeaderImgID { get; set; }
        public string ImageLocation { get; set; }
        public string ImageName { get; set; }
    
        public virtual ICollection<Flyer_Flyer> Flyer_Flyer { get; set; }
    }
}
