//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flyer_PlaceHolder
    {
        public Flyer_PlaceHolder()
        {
            this.Flyer_Logo = new HashSet<Flyer_Logo>();
        }
    
        public int PlaceHolderID { get; set; }
        public Nullable<int> PlaceHolderLocationID { get; set; }
        public Nullable<int> PoductID { get; set; }
    
        public virtual ICollection<Flyer_Logo> Flyer_Logo { get; set; }
        public virtual Flyer_PlaceHolderLocation Flyer_PlaceHolderLocation { get; set; }
        public virtual Flyer_Product Flyer_Product { get; set; }
    }
}
