//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flyer_LogoType
    {
        public Flyer_LogoType()
        {
            this.Flyer_Logo = new HashSet<Flyer_Logo>();
        }
    
        public int LogoTypeID { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<Flyer_Logo> Flyer_Logo { get; set; }
    }
}
