//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flyer_TemplateType
    {
        public Flyer_TemplateType()
        {
            this.Flyer_Template = new HashSet<Flyer_Template>();
        }
    
        public int TypeID { get; set; }
        public string TypeDescription { get; set; }
    
        public virtual ICollection<Flyer_Template> Flyer_Template { get; set; }
    }
}
