//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class flyer_template_preference1
    {
        public int id { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public Nullable<int> PreferenceId { get; set; }
    }
}
