//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flyer_Template_Preference
    {
        public int ID { get; set; }
        public int TemplateID { get; set; }
        public int PreferenceID { get; set; }
    
        public virtual Flyer_Preference Flyer_Preference { get; set; }
        public virtual Flyer_Template Flyer_Template { get; set; }
    }
}
