//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flyer_PlaceHolderLocation
    {
        public int TemplateContentLocationID { get; set; }
        public Nullable<int> XCoordinate { get; set; }
        public Nullable<int> YCoordinate { get; set; }
        public Nullable<int> TopLeft { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
    
        public virtual Flyer_PlaceHolder Flyer_PlaceHolder { get; set; }
    }
}
