//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flyer_ImageEditorData
    {
        public int ImageId { get; set; }
        public int TemplateID { get; set; }
        public string SerializedData { get; set; }
        public string Sequence { get; set; }
        public string PositionX { get; set; }
        public string PositionY { get; set; }
        public string Width { get; set; }
        public string Height { get; set; }
        public string Rotation { get; set; }
        public string ProductID { get; set; }
        public string VObjectType { get; set; }
        public string Font { get; set; }
        public string FontSize { get; set; }
        public string FontColor { get; set; }
        public string Bold { get; set; }
        public string Italic { get; set; }
        public string Underline { get; set; }
        public string ScaleX { get; set; }
        public string ScaleY { get; set; }
        public string TranslatedX { get; set; }
        public string TranslatedY { get; set; }
        public string Text { get; set; }
        public string ImageRotation { get; set; }
    }
}
