//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flyer_Logo
    {
        public int LogoID { get; set; }
        public Nullable<int> PlaceHolderID { get; set; }
        public Nullable<int> LogoTypeID { get; set; }
        public Nullable<int> LogoFileID { get; set; }
        public string LogoFileLocation { get; set; }
    
        public virtual Flyer_LogoType Flyer_LogoType { get; set; }
        public virtual Flyer_PlaceHolder Flyer_PlaceHolder { get; set; }
    }
}
