//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HtmlTextLog
    {
        public int HtmlTextLogID { get; set; }
        public int ItemID { get; set; }
        public int StateID { get; set; }
        public string Comment { get; set; }
        public bool Approved { get; set; }
        public int CreatedByUserID { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
    
        public virtual HtmlText HtmlText { get; set; }
        public virtual WorkflowState WorkflowState { get; set; }
    }
}
