//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HtmlText
    {
        public HtmlText()
        {
            this.HtmlTextLogs = new HashSet<HtmlTextLog>();
            this.HtmlTextUsers = new HashSet<HtmlTextUser>();
        }
    
        public int ModuleID { get; set; }
        public int ItemID { get; set; }
        public string Content { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public string Summary { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual WorkflowState WorkflowState { get; set; }
        public virtual ICollection<HtmlTextLog> HtmlTextLogs { get; set; }
        public virtual ICollection<HtmlTextUser> HtmlTextUsers { get; set; }
    }
}
