//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaData
    {
        public MetaData()
        {
            this.ContentItems_MetaData = new HashSet<ContentItems_MetaData>();
        }
    
        public int MetaDataID { get; set; }
        public string MetaDataName { get; set; }
        public string MetaDataDescription { get; set; }
    
        public virtual ICollection<ContentItems_MetaData> ContentItems_MetaData { get; set; }
    }
}
