//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mobile_RedirectionRules
    {
        public int Id { get; set; }
        public int RedirectionId { get; set; }
        public string Capability { get; set; }
        public string Expression { get; set; }
    
        public virtual Mobile_Redirections Mobile_Redirections { get; set; }
    }
}
