//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mobile_Redirections
    {
        public Mobile_Redirections()
        {
            this.Mobile_RedirectionRules = new HashSet<Mobile_RedirectionRules>();
        }
    
        public int Id { get; set; }
        public int PortalId { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public int SortOrder { get; set; }
        public int SourceTabId { get; set; }
        public bool IncludeChildTabs { get; set; }
        public int TargetType { get; set; }
        public string TargetValue { get; set; }
        public bool Enabled { get; set; }
        public int CreatedByUserID { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int LastModifiedByUserID { get; set; }
        public System.DateTime LastModifiedOnDate { get; set; }
    
        public virtual ICollection<Mobile_RedirectionRules> Mobile_RedirectionRules { get; set; }
        public virtual Portal Portal { get; set; }
    }
}
