//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageType
    {
        public PackageType()
        {
            this.Packages = new HashSet<Package>();
        }
    
        public string PackageType1 { get; set; }
        public string Description { get; set; }
        public int SecurityAccessLevel { get; set; }
        public string EditorControlSrc { get; set; }
    
        public virtual ICollection<Package> Packages { get; set; }
    }
}
