//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public Package()
        {
            this.Assemblies = new HashSet<Assembly>();
            this.Authentications = new HashSet<Authentication>();
            this.Dashboard_Controls = new HashSet<Dashboard_Controls>();
            this.DesktopModules = new HashSet<DesktopModule>();
            this.LanguagePacks = new HashSet<LanguagePack>();
            this.SkinControls = new HashSet<SkinControl>();
            this.SkinPackages = new HashSet<SkinPackage>();
        }
    
        public int PackageID { get; set; }
        public Nullable<int> PortalID { get; set; }
        public string Name { get; set; }
        public string FriendlyName { get; set; }
        public string Description { get; set; }
        public string PackageType { get; set; }
        public string Version { get; set; }
        public string License { get; set; }
        public string Manifest { get; set; }
        public string Owner { get; set; }
        public string Organization { get; set; }
        public string Url { get; set; }
        public string Email { get; set; }
        public string ReleaseNotes { get; set; }
        public bool IsSystemPackage { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public string FolderName { get; set; }
        public string IconFile { get; set; }
    
        public virtual ICollection<Assembly> Assemblies { get; set; }
        public virtual ICollection<Authentication> Authentications { get; set; }
        public virtual ICollection<Dashboard_Controls> Dashboard_Controls { get; set; }
        public virtual ICollection<DesktopModule> DesktopModules { get; set; }
        public virtual ICollection<LanguagePack> LanguagePacks { get; set; }
        public virtual PackageType PackageType1 { get; set; }
        public virtual ICollection<SkinControl> SkinControls { get; set; }
        public virtual ICollection<SkinPackage> SkinPackages { get; set; }
    }
}
