//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.DesktopModulePermissions = new HashSet<DesktopModulePermission>();
            this.FolderPermissions = new HashSet<FolderPermission>();
            this.ModulePermissions = new HashSet<ModulePermission>();
            this.TabPermissions = new HashSet<TabPermission>();
        }
    
        public int PermissionID { get; set; }
        public string PermissionCode { get; set; }
        public int ModuleDefID { get; set; }
        public string PermissionKey { get; set; }
        public string PermissionName { get; set; }
        public int ViewOrder { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
    
        public virtual ICollection<DesktopModulePermission> DesktopModulePermissions { get; set; }
        public virtual ICollection<FolderPermission> FolderPermissions { get; set; }
        public virtual ICollection<ModulePermission> ModulePermissions { get; set; }
        public virtual ICollection<TabPermission> TabPermissions { get; set; }
    }
}
