//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortalLocalization
    {
        public int PortalID { get; set; }
        public string CultureCode { get; set; }
        public string PortalName { get; set; }
        public string LogoFile { get; set; }
        public string FooterText { get; set; }
        public string Description { get; set; }
        public string KeyWords { get; set; }
        public string BackgroundFile { get; set; }
        public Nullable<int> HomeTabId { get; set; }
        public Nullable<int> LoginTabId { get; set; }
        public Nullable<int> UserTabId { get; set; }
        public Nullable<int> AdminTabId { get; set; }
        public Nullable<int> SplashTabId { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public Nullable<int> RegisterTabId { get; set; }
        public Nullable<int> SearchTabId { get; set; }
    
        public virtual Portal Portal { get; set; }
    }
}
