//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skin
    {
        public int SkinID { get; set; }
        public int SkinPackageID { get; set; }
        public string SkinSrc { get; set; }
    
        public virtual SkinPackage SkinPackage { get; set; }
    }
}
