//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAA_ProductSizes
    {
        public int SizeID { get; set; }
        public int ProductID { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Depth { get; set; }
        public Nullable<double> Volume { get; set; }
    
        public virtual CAT_Products CAT_Products { get; set; }
        public virtual TAA_Sizes TAA_Sizes { get; set; }
    }
}
