//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAA_Products
    {
        public int ProductID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string ItemCode { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string ImageURL { get; set; }
        public Nullable<int> SizeID { get; set; }
    
        public virtual TAA_ProductCategories TAA_ProductCategories { get; set; }
    }
}
