//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAA_vw_ProductsInOrders
    {
        public int ProductID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Category2ID { get; set; }
        public string Category3 { get; set; }
        public string ProductName { get; set; }
        public string ProductNumber { get; set; }
        public string EAN { get; set; }
        public string ISBN { get; set; }
        public string Free1 { get; set; }
        public string Free2 { get; set; }
        public string Free3 { get; set; }
        public string KeyWords { get; set; }
        public string ProductImage { get; set; }
        public decimal UnitCost { get; set; }
        public Nullable<decimal> UnitCost2 { get; set; }
        public Nullable<decimal> UnitCost3 { get; set; }
        public Nullable<decimal> UnitCost4 { get; set; }
        public Nullable<decimal> UnitCost5 { get; set; }
        public Nullable<decimal> UnitCost6 { get; set; }
        public string Description { get; set; }
        public string DescriptionHTML { get; set; }
        public string URL { get; set; }
        public Nullable<int> Stock { get; set; }
        public string OrderQuant { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> FreightCosts1 { get; set; }
        public Nullable<decimal> FreightCosts2 { get; set; }
        public bool Featured { get; set; }
        public decimal SalePrice { get; set; }
        public Nullable<System.DateTime> SaleStart { get; set; }
        public Nullable<System.DateTime> SaleEnd { get; set; }
        public Nullable<bool> DownLoad { get; set; }
        public string ZIPPassWord { get; set; }
        public string DownLoadFile { get; set; }
        public Nullable<bool> Archive { get; set; }
        public int CreatedByUser { get; set; }
        public int BulkPriceLimit1 { get; set; }
        public int BulkPriceLimit2 { get; set; }
        public int BulkPriceLimit3 { get; set; }
        public int BulkPriceLimit4 { get; set; }
        public int BulkPriceLimit5 { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> SubscriptionPeriod { get; set; }
        public Nullable<bool> RecurringBilling { get; set; }
        public Nullable<bool> TaxExempt { get; set; }
        public Nullable<bool> ShipExempt { get; set; }
        public decimal InsuredValue { get; set; }
        public Nullable<System.DateTime> PublicationStart { get; set; }
        public Nullable<System.DateTime> PublicationEnd { get; set; }
        public string Status { get; set; }
        public bool DonationItem { get; set; }
        public bool PayPalSubscription { get; set; }
        public bool UseRoleFees { get; set; }
        public decimal ProductCost { get; set; }
        public string RoleExpiryType { get; set; }
        public string ItemDeliveryType { get; set; }
        public int ReorderPoint { get; set; }
        public string OrderQuantValidExpr { get; set; }
        public string ShippingAddress { get; set; }
        public Nullable<int> OrigProductID { get; set; }
        public bool AuctionFinished { get; set; }
        public Nullable<decimal> StartingPrice { get; set; }
        public Nullable<decimal> ReservePrice { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public string TaxCode { get; set; }
        public Nullable<decimal> MaxWeight { get; set; }
        public Nullable<int> TotalPeriods { get; set; }
        public Nullable<bool> NonStockItem { get; set; }
        public Nullable<decimal> DealerTier1Price { get; set; }
        public Nullable<decimal> DealerTier2Price { get; set; }
        public Nullable<decimal> DealerTier3Price { get; set; }
        public Nullable<decimal> DealerTier4Price { get; set; }
        public Nullable<decimal> ConsumerTier1Price { get; set; }
        public Nullable<decimal> ConsumerTier2Price { get; set; }
        public Nullable<decimal> ConsumerTier3Price { get; set; }
        public Nullable<decimal> ConsumerTier4Price { get; set; }
        public string DiscountClass { get; set; }
        public Nullable<int> CMSProductID { get; set; }
        public int OrderDetailsID { get; set; }
        public int OrderID { get; set; }
        public int QuantityRemaining { get; set; }
        public decimal ProductUnitCost { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> InvoiceShipCosts { get; set; }
        public Nullable<int> CreditNoteNumber { get; set; }
        public Nullable<System.DateTime> CreditNoteDate { get; set; }
        public Nullable<decimal> CreditNoteShipCosts { get; set; }
        public string Options { get; set; }
        public Nullable<System.DateTime> AllocDate { get; set; }
        public Nullable<System.DateTime> SubscrExpiryDate { get; set; }
        public int RecordID { get; set; }
        public Nullable<int> BaseRecID { get; set; }
        public Nullable<int> ProductSlotID { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public decimal ReferrerCommission { get; set; }
        public decimal VendorCommission { get; set; }
        public string ShippingCompany { get; set; }
        public string TrackingNumber { get; set; }
        public int DeliveredUnits { get; set; }
        public string SKU { get; set; }
        public decimal orderDetailsProductCost { get; set; }
        public int BillingPeriod { get; set; }
        public decimal Tax2 { get; set; }
        public Nullable<int> CouponCodeID { get; set; }
        public Nullable<int> CartPriceRuleID { get; set; }
        public Nullable<decimal> LoyaltyDiscount { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> OrderDetailsLastModfiedBy { get; set; }
        public Nullable<System.DateTime> orderDetailsLastModfiedOnDate { get; set; }
        public Nullable<int> PeriodsRemaining { get; set; }
        public int CartID { get; set; }
        public int MicrositeID { get; set; }
        public Nullable<int> RoleCardID { get; set; }
        public Nullable<int> FanID { get; set; }
        public Nullable<decimal> BulkDiscount { get; set; }
        public Nullable<int> SizeXS { get; set; }
        public Nullable<int> SizeS { get; set; }
        public Nullable<int> SizeM { get; set; }
        public Nullable<int> SizeL { get; set; }
        public Nullable<int> SizeXL { get; set; }
        public Nullable<int> SizeXXL { get; set; }
        public string PrintedName { get; set; }
        public Nullable<int> JerseyNumber { get; set; }
        public string TeamName { get; set; }
        public string PrimaryColor { get; set; }
        public Nullable<int> PrimaryColorID { get; set; }
        public string SecondaryColor { get; set; }
        public Nullable<int> SecondaryColorID { get; set; }
        public string Accent { get; set; }
        public Nullable<int> AccentColorID { get; set; }
        public string TeamLogo { get; set; }
        public string School { get; set; }
        public string City { get; set; }
        public string Sport { get; set; }
        public Nullable<int> orderDetailsCreatedBy { get; set; }
        public Nullable<System.DateTime> shoppingCartCreatedDate { get; set; }
        public Nullable<int> shoppingCartLastModifiedBy { get; set; }
        public Nullable<System.DateTime> shoppingCartLastModified { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> DeletedByUserID { get; set; }
        public Nullable<System.DateTime> DeletedOnDate { get; set; }
        public string sizeDisplayname { get; set; }
        public int sizeQuantity { get; set; }
        public int SizeID { get; set; }
        public int Quantity { get; set; }
        public string CMSProductDesign { get; set; }
        public string Sizenumber { get; set; }
    }
}
