//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAA_Emails
    {
        public long EmailID { get; set; }
        public int MicrositeID { get; set; }
        public int FromUserID { get; set; }
        public Nullable<int> ToUserID { get; set; }
        public string ToAddress { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Attachments { get; set; }
        public bool EmailSent { get; set; }
        public Nullable<System.DateTime> EmailSentDate { get; set; }
    }
}
