//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAA_ProductCategories
    {
        public TAA_ProductCategories()
        {
            this.TAA_Products = new HashSet<TAA_Products>();
        }
    
        public int CategoryID { get; set; }
        public Nullable<int> ParentCatID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<TAA_Products> TAA_Products { get; set; }
    }
}
