//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAA_Notifications
    {
        public int NotificationID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> MicrositeID { get; set; }
        public string Notification { get; set; }
        public string NotificationType { get; set; }
        public string Details { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> DeletedByUserID { get; set; }
        public Nullable<System.DateTime> DeletedOnDate { get; set; }
    }
}
