//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAA_FanID
    {
        public int MicrositeID { get; set; }
        public int FanID { get; set; }
        public string DesignName { get; set; }
        public string TeamName { get; set; }
        public string PrimaryColor { get; set; }
        public Nullable<int> PrimaryColorID { get; set; }
        public string SecondaryColor { get; set; }
        public Nullable<int> SecondaryColorID { get; set; }
        public string Accent { get; set; }
        public Nullable<int> AccentColorID { get; set; }
        public string TeamLogo { get; set; }
        public string School { get; set; }
        public string City { get; set; }
        public string Sport { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> DeletedByUserID { get; set; }
        public Nullable<System.DateTime> DeletedOnDate { get; set; }
        public Nullable<int> TAASportID { get; set; }
        public string UserUploadedGraphic { get; set; }
        public string GAUploadedGraphic { get; set; }
        public Nullable<bool> CUG { get; set; }
        public Nullable<bool> GraphicDeleted { get; set; }
        public Nullable<bool> CUGGoodsize { get; set; }
        public Nullable<bool> CUGGoodtransparancy { get; set; }
        public Nullable<bool> CUGGoodvectorized { get; set; }
        public Nullable<bool> CUGGoodresolution { get; set; }
    }
}
