//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAA_Sports
    {
        public TAA_Sports()
        {
            this.TAA_Microsite = new HashSet<TAA_Microsite>();
        }
    
        public int SportID { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> DeletedByUserID { get; set; }
        public Nullable<System.DateTime> DeletedOnDate { get; set; }
    
        public virtual ICollection<TAA_Microsite> TAA_Microsite { get; set; }
    }
}
