//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAA_RoleCards
    {
        public int RoleCardID { get; set; }
        public int RoleCallSheetID { get; set; }
        public string PrintedName { get; set; }
        public Nullable<int> JerseyNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleInitial { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Gender { get; set; }
        public int SizeGroupID { get; set; }
        public int PantSizeID { get; set; }
        public int ShirtSizeID { get; set; }
        public string playerRetrievalCode { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> DeletedByUserID { get; set; }
        public Nullable<System.DateTime> DeletedOnDate { get; set; }
    
        public virtual TAA_PantSizes TAA_PantSizes { get; set; }
        public virtual TAA_RoleCallSheets TAA_RoleCallSheets { get; set; }
        public virtual TAA_ShirtSizes TAA_ShirtSizes { get; set; }
    }
}
