//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAA_Coupons
    {
        public TAA_Coupons()
        {
            this.TAA_CouponAdjustments = new HashSet<TAA_CouponAdjustments>();
        }
    
        public int CouponID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string AxapterPromoNumber { get; set; }
        public string AxapterPromoDescription { get; set; }
        public string CouponCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> StartQty { get; set; }
        public Nullable<int> EndQty { get; set; }
        public Nullable<decimal> StartPrice { get; set; }
        public Nullable<decimal> EndPrice { get; set; }
        public int MaxUsage { get; set; }
        public int MaxUsagePerUser { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public int CreatedByUserID { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> DeletedByUserID { get; set; }
        public Nullable<System.DateTime> DeletedOnDate { get; set; }
    
        public virtual ICollection<TAA_CouponAdjustments> TAA_CouponAdjustments { get; set; }
    }
}
