//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAA_Adjustments
    {
        public TAA_Adjustments()
        {
            this.TAA_ShoppingCartAdjustments = new HashSet<TAA_ShoppingCartAdjustments>();
            this.TAA_OrdersAdjustments = new HashSet<TAA_OrdersAdjustments>();
        }
    
        public int AdjustmentID { get; set; }
        public string Description { get; set; }
        public string PromotionNumber { get; set; }
        public string AdjustmentType { get; set; }
        public string DefaultValue { get; set; }
    
        public virtual ICollection<TAA_ShoppingCartAdjustments> TAA_ShoppingCartAdjustments { get; set; }
        public virtual ICollection<TAA_OrdersAdjustments> TAA_OrdersAdjustments { get; set; }
    }
}
