//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAA_ShoppingCart
    {
        public TAA_ShoppingCart()
        {
            this.TAA_ShoppingCartSizes = new HashSet<TAA_ShoppingCartSizes>();
        }
    
        public int CartID { get; set; }
        public int RecordID { get; set; }
        public int ProductID { get; set; }
        public int MicrositeID { get; set; }
        public Nullable<int> RoleCardID { get; set; }
        public Nullable<int> FanID { get; set; }
        public Nullable<decimal> BulkDiscount { get; set; }
        public Nullable<int> SizeXS { get; set; }
        public Nullable<int> SizeS { get; set; }
        public Nullable<int> SizeM { get; set; }
        public Nullable<int> SizeL { get; set; }
        public Nullable<int> SizeXL { get; set; }
        public Nullable<int> SizeXXL { get; set; }
        public string PrintedName { get; set; }
        public Nullable<int> JerseyNumber { get; set; }
        public string TeamName { get; set; }
        public string PrimaryColor { get; set; }
        public Nullable<int> PrimaryColorID { get; set; }
        public string SecondaryColor { get; set; }
        public Nullable<int> SecondaryColorID { get; set; }
        public string Accent { get; set; }
        public Nullable<int> AccentColorID { get; set; }
        public string TeamLogo { get; set; }
        public string School { get; set; }
        public string City { get; set; }
        public string Sport { get; set; }
        public string Initials { get; set; }
        public string InitialOne { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> DeletedByUserID { get; set; }
        public Nullable<System.DateTime> DeletedOnDate { get; set; }
    
        public virtual CAT_Products CAT_Products { get; set; }
        public virtual ICollection<TAA_ShoppingCartSizes> TAA_ShoppingCartSizes { get; set; }
    }
}
