//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAA_Microsite
    {
        public TAA_Microsite()
        {
            this.TAA_MicrositeLogos = new HashSet<TAA_MicrositeLogos>();
        }
    
        public int MicrositeID { get; set; }
        public string TeamName { get; set; }
        public string PrimaryColour { get; set; }
        public string SecondaryColour { get; set; }
        public string Accent { get; set; }
        public Nullable<int> PrimaryColorID { get; set; }
        public Nullable<int> SecondaryColorID { get; set; }
        public Nullable<int> AccentColorID { get; set; }
        public string TeamLogo { get; set; }
        public string School { get; set; }
        public string City { get; set; }
        public string Sport { get; set; }
        public Nullable<int> SportID { get; set; }
        public Nullable<bool> CreatedFromSLP { get; set; }
        public bool Enabled { get; set; }
        public bool Locked { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> DeletedByUserID { get; set; }
        public Nullable<System.DateTime> DeletedOnDate { get; set; }
        public string URL { get; set; }
        public string PartialURL { get; set; }
        public string TeamUniqueID { get; set; }
        public string IntegratorRetrievalCode { get; set; }
        public Nullable<int> IntegratorCustAccount { get; set; }
    
        public virtual TAA_Sports TAA_Sports { get; set; }
        public virtual ICollection<TAA_MicrositeLogos> TAA_MicrositeLogos { get; set; }
    }
}
