//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAA_ShippingBoxes
    {
        public int OrderID { get; set; }
        public int BoxID { get; set; }
        public string BoxSize { get; set; }
        public Nullable<decimal> DeclaredWeight { get; set; }
        public Nullable<decimal> BoxWeight { get; set; }
        public Nullable<decimal> DimensionalWeight { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public Nullable<bool> IsDimensionalWeightApplied { get; set; }
        public Nullable<decimal> BaseRate { get; set; }
        public Nullable<decimal> FreightCharge { get; set; }
        public Nullable<decimal> BoxValue { get; set; }
        public Nullable<decimal> AreaDelierySurcharge { get; set; }
        public Nullable<decimal> GroundFuelSurcharge { get; set; }
        public Nullable<decimal> AirFuelSurcharge { get; set; }
        public Nullable<decimal> TotalFuelSurcharge { get; set; }
        public Nullable<decimal> SaturdayDeliverySurcharge { get; set; }
        public Nullable<decimal> ExpressDeliverySurcharge { get; set; }
        public Nullable<decimal> GroundToResidentialSurcharge { get; set; }
        public Nullable<decimal> AirToResidentialSurcharge { get; set; }
        public Nullable<decimal> CODSurcharge { get; set; }
        public Nullable<decimal> Insurance { get; set; }
    }
}
