//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAA_OrdersAdjustments
    {
        public int id { get; set; }
        public Nullable<int> AdjustmentID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string PromotionValue { get; set; }
        public Nullable<double> FanoramaTierPercentage { get; set; }
        public Nullable<decimal> TotalAdjustment { get; set; }
    
        public virtual CAT_Orders CAT_Orders { get; set; }
        public virtual TAA_Adjustments TAA_Adjustments { get; set; }
    }
}
