//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxonomy_ScopeTypes
    {
        public Taxonomy_ScopeTypes()
        {
            this.Taxonomy_Vocabularies = new HashSet<Taxonomy_Vocabularies>();
        }
    
        public int ScopeTypeID { get; set; }
        public string ScopeType { get; set; }
    
        public virtual ICollection<Taxonomy_Vocabularies> Taxonomy_Vocabularies { get; set; }
    }
}
