//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrlTracking
    {
        public UrlTracking()
        {
            this.UrlLogs = new HashSet<UrlLog>();
        }
    
        public int UrlTrackingID { get; set; }
        public Nullable<int> PortalID { get; set; }
        public string Url { get; set; }
        public string UrlType { get; set; }
        public int Clicks { get; set; }
        public Nullable<System.DateTime> LastClick { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool LogActivity { get; set; }
        public bool TrackClicks { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public bool NewWindow { get; set; }
    
        public virtual Portal Portal { get; set; }
        public virtual ICollection<UrlLog> UrlLogs { get; set; }
    }
}
