//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CAT_CreditNotes = new HashSet<CAT_CreditNotes>();
            this.CAT_Feedbacks = new HashSet<CAT_Feedbacks>();
            this.CAT_Orders = new HashSet<CAT_Orders>();
            this.CAT_PaymentMethodPermission = new HashSet<CAT_PaymentMethodPermission>();
            this.CAT_ProductPermission = new HashSet<CAT_ProductPermission>();
            this.CAT_Referrals = new HashSet<CAT_Referrals>();
            this.CAT_ShipTo = new HashSet<CAT_ShipTo>();
            this.CAT_Threads = new HashSet<CAT_Threads>();
            this.CAT_VendorPermission = new HashSet<CAT_VendorPermission>();
            this.DesktopModulePermissions = new HashSet<DesktopModulePermission>();
            this.FolderPermissions = new HashSet<FolderPermission>();
            this.ModulePermissions = new HashSet<ModulePermission>();
            this.Profiles = new HashSet<Profile>();
            this.TabPermissions = new HashSet<TabPermission>();
            this.UserAuthentications = new HashSet<UserAuthentication>();
            this.UserPortals = new HashSet<UserPortal>();
            this.UserProfiles = new HashSet<UserProfile>();
            this.UserRoles = new HashSet<UserRole>();
            this.UsersOnlines = new HashSet<UsersOnline>();
            this.TAA_PaymentTerms = new HashSet<TAA_PaymentTerms>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool IsSuperUser { get; set; }
        public Nullable<int> AffiliateId { get; set; }
        public string Email { get; set; }
        public string DisplayName { get; set; }
        public bool UpdatePassword { get; set; }
        public string LastIPAddress { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
    
        public virtual ICollection<CAT_CreditNotes> CAT_CreditNotes { get; set; }
        public virtual ICollection<CAT_Feedbacks> CAT_Feedbacks { get; set; }
        public virtual ICollection<CAT_Orders> CAT_Orders { get; set; }
        public virtual CAT_Organization CAT_Organization { get; set; }
        public virtual ICollection<CAT_PaymentMethodPermission> CAT_PaymentMethodPermission { get; set; }
        public virtual ICollection<CAT_ProductPermission> CAT_ProductPermission { get; set; }
        public virtual ICollection<CAT_Referrals> CAT_Referrals { get; set; }
        public virtual ICollection<CAT_ShipTo> CAT_ShipTo { get; set; }
        public virtual ICollection<CAT_Threads> CAT_Threads { get; set; }
        public virtual ICollection<CAT_VendorPermission> CAT_VendorPermission { get; set; }
        public virtual ICollection<DesktopModulePermission> DesktopModulePermissions { get; set; }
        public virtual ICollection<FolderPermission> FolderPermissions { get; set; }
        public virtual ICollection<ModulePermission> ModulePermissions { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
        public virtual ICollection<TabPermission> TabPermissions { get; set; }
        public virtual ICollection<UserAuthentication> UserAuthentications { get; set; }
        public virtual ICollection<UserPortal> UserPortals { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual ICollection<UsersOnline> UsersOnlines { get; set; }
        public virtual ICollection<TAA_PaymentTerms> TAA_PaymentTerms { get; set; }
    }
}
