//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowState
    {
        public WorkflowState()
        {
            this.HtmlTexts = new HashSet<HtmlText>();
            this.HtmlTextLogs = new HashSet<HtmlTextLog>();
        }
    
        public int StateID { get; set; }
        public int WorkflowID { get; set; }
        public string StateName { get; set; }
        public int Order { get; set; }
        public bool IsActive { get; set; }
        public bool Notify { get; set; }
    
        public virtual ICollection<HtmlText> HtmlTexts { get; set; }
        public virtual ICollection<HtmlTextLog> HtmlTextLogs { get; set; }
        public virtual Workflow Workflow { get; set; }
    }
}
