//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace NewTweaker
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dnnolddescriptionEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dnnolddescriptionEntities object using the connection string found in the 'dnnolddescriptionEntities' section of the application configuration file.
        /// </summary>
        public dnnolddescriptionEntities() : base("name=dnnolddescriptionEntities", "dnnolddescriptionEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dnnolddescriptionEntities object.
        /// </summary>
        public dnnolddescriptionEntities(string connectionString) : base(connectionString, "dnnolddescriptionEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dnnolddescriptionEntities object.
        /// </summary>
        public dnnolddescriptionEntities(EntityConnection connection) : base(connection, "dnnolddescriptionEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CAT_Products> CAT_Products
        {
            get
            {
                if ((_CAT_Products == null))
                {
                    _CAT_Products = base.CreateObjectSet<CAT_Products>("CAT_Products");
                }
                return _CAT_Products;
            }
        }
        private ObjectSet<CAT_Products> _CAT_Products;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CAT_Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCAT_Products(CAT_Products cAT_Products)
        {
            base.AddObject("CAT_Products", cAT_Products);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dnnolddescriptionModel", Name="CAT_Products")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CAT_Products : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CAT_Products object.
        /// </summary>
        /// <param name="productID">Initial value of the ProductID property.</param>
        /// <param name="unitCost">Initial value of the UnitCost property.</param>
        /// <param name="descriptionHTML">Initial value of the DescriptionHTML property.</param>
        /// <param name="orderQuant">Initial value of the OrderQuant property.</param>
        /// <param name="featured">Initial value of the Featured property.</param>
        /// <param name="salePrice">Initial value of the SalePrice property.</param>
        /// <param name="createdByUser">Initial value of the CreatedByUser property.</param>
        /// <param name="bulkPriceLimit1">Initial value of the BulkPriceLimit1 property.</param>
        /// <param name="bulkPriceLimit2">Initial value of the BulkPriceLimit2 property.</param>
        /// <param name="bulkPriceLimit3">Initial value of the BulkPriceLimit3 property.</param>
        /// <param name="bulkPriceLimit4">Initial value of the BulkPriceLimit4 property.</param>
        /// <param name="bulkPriceLimit5">Initial value of the BulkPriceLimit5 property.</param>
        /// <param name="insuredValue">Initial value of the InsuredValue property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="donationItem">Initial value of the DonationItem property.</param>
        /// <param name="payPalSubscription">Initial value of the PayPalSubscription property.</param>
        /// <param name="useRoleFees">Initial value of the UseRoleFees property.</param>
        /// <param name="productCost">Initial value of the ProductCost property.</param>
        /// <param name="roleExpiryType">Initial value of the RoleExpiryType property.</param>
        /// <param name="itemDeliveryType">Initial value of the ItemDeliveryType property.</param>
        /// <param name="reorderPoint">Initial value of the ReorderPoint property.</param>
        /// <param name="orderQuantValidExpr">Initial value of the OrderQuantValidExpr property.</param>
        /// <param name="shippingAddress">Initial value of the ShippingAddress property.</param>
        /// <param name="auctionFinished">Initial value of the AuctionFinished property.</param>
        public static CAT_Products CreateCAT_Products(global::System.Int32 productID, global::System.Decimal unitCost, global::System.String descriptionHTML, global::System.String orderQuant, global::System.Boolean featured, global::System.Decimal salePrice, global::System.Int32 createdByUser, global::System.Int32 bulkPriceLimit1, global::System.Int32 bulkPriceLimit2, global::System.Int32 bulkPriceLimit3, global::System.Int32 bulkPriceLimit4, global::System.Int32 bulkPriceLimit5, global::System.Decimal insuredValue, global::System.String status, global::System.Boolean donationItem, global::System.Boolean payPalSubscription, global::System.Boolean useRoleFees, global::System.Decimal productCost, global::System.String roleExpiryType, global::System.String itemDeliveryType, global::System.Int32 reorderPoint, global::System.String orderQuantValidExpr, global::System.String shippingAddress, global::System.Boolean auctionFinished)
        {
            CAT_Products cAT_Products = new CAT_Products();
            cAT_Products.ProductID = productID;
            cAT_Products.UnitCost = unitCost;
            cAT_Products.DescriptionHTML = descriptionHTML;
            cAT_Products.OrderQuant = orderQuant;
            cAT_Products.Featured = featured;
            cAT_Products.SalePrice = salePrice;
            cAT_Products.CreatedByUser = createdByUser;
            cAT_Products.BulkPriceLimit1 = bulkPriceLimit1;
            cAT_Products.BulkPriceLimit2 = bulkPriceLimit2;
            cAT_Products.BulkPriceLimit3 = bulkPriceLimit3;
            cAT_Products.BulkPriceLimit4 = bulkPriceLimit4;
            cAT_Products.BulkPriceLimit5 = bulkPriceLimit5;
            cAT_Products.InsuredValue = insuredValue;
            cAT_Products.Status = status;
            cAT_Products.DonationItem = donationItem;
            cAT_Products.PayPalSubscription = payPalSubscription;
            cAT_Products.UseRoleFees = useRoleFees;
            cAT_Products.ProductCost = productCost;
            cAT_Products.RoleExpiryType = roleExpiryType;
            cAT_Products.ItemDeliveryType = itemDeliveryType;
            cAT_Products.ReorderPoint = reorderPoint;
            cAT_Products.OrderQuantValidExpr = orderQuantValidExpr;
            cAT_Products.ShippingAddress = shippingAddress;
            cAT_Products.AuctionFinished = auctionFinished;
            return cAT_Products;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                if (_ProductID != value)
                {
                    OnProductIDChanging(value);
                    ReportPropertyChanging("ProductID");
                    _ProductID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductID");
                    OnProductIDChanged();
                }
            }
        }
        private global::System.Int32 _ProductID;
        partial void OnProductIDChanging(global::System.Int32 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CategoryID
        {
            get
            {
                return _CategoryID;
            }
            set
            {
                OnCategoryIDChanging(value);
                ReportPropertyChanging("CategoryID");
                _CategoryID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryID");
                OnCategoryIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CategoryID;
        partial void OnCategoryIDChanging(Nullable<global::System.Int32> value);
        partial void OnCategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Category2ID
        {
            get
            {
                return _Category2ID;
            }
            set
            {
                OnCategory2IDChanging(value);
                ReportPropertyChanging("Category2ID");
                _Category2ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Category2ID");
                OnCategory2IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Category2ID;
        partial void OnCategory2IDChanging(Nullable<global::System.Int32> value);
        partial void OnCategory2IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Category3
        {
            get
            {
                return _Category3;
            }
            set
            {
                OnCategory3Changing(value);
                ReportPropertyChanging("Category3");
                _Category3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Category3");
                OnCategory3Changed();
            }
        }
        private global::System.String _Category3;
        partial void OnCategory3Changing(global::System.String value);
        partial void OnCategory3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductNumber
        {
            get
            {
                return _ProductNumber;
            }
            set
            {
                OnProductNumberChanging(value);
                ReportPropertyChanging("ProductNumber");
                _ProductNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductNumber");
                OnProductNumberChanged();
            }
        }
        private global::System.String _ProductNumber;
        partial void OnProductNumberChanging(global::System.String value);
        partial void OnProductNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EAN
        {
            get
            {
                return _EAN;
            }
            set
            {
                OnEANChanging(value);
                ReportPropertyChanging("EAN");
                _EAN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EAN");
                OnEANChanged();
            }
        }
        private global::System.String _EAN;
        partial void OnEANChanging(global::System.String value);
        partial void OnEANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ISBN
        {
            get
            {
                return _ISBN;
            }
            set
            {
                OnISBNChanging(value);
                ReportPropertyChanging("ISBN");
                _ISBN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ISBN");
                OnISBNChanged();
            }
        }
        private global::System.String _ISBN;
        partial void OnISBNChanging(global::System.String value);
        partial void OnISBNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Free1
        {
            get
            {
                return _Free1;
            }
            set
            {
                OnFree1Changing(value);
                ReportPropertyChanging("Free1");
                _Free1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Free1");
                OnFree1Changed();
            }
        }
        private global::System.String _Free1;
        partial void OnFree1Changing(global::System.String value);
        partial void OnFree1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Free2
        {
            get
            {
                return _Free2;
            }
            set
            {
                OnFree2Changing(value);
                ReportPropertyChanging("Free2");
                _Free2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Free2");
                OnFree2Changed();
            }
        }
        private global::System.String _Free2;
        partial void OnFree2Changing(global::System.String value);
        partial void OnFree2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Free3
        {
            get
            {
                return _Free3;
            }
            set
            {
                OnFree3Changing(value);
                ReportPropertyChanging("Free3");
                _Free3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Free3");
                OnFree3Changed();
            }
        }
        private global::System.String _Free3;
        partial void OnFree3Changing(global::System.String value);
        partial void OnFree3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KeyWords
        {
            get
            {
                return _KeyWords;
            }
            set
            {
                OnKeyWordsChanging(value);
                ReportPropertyChanging("KeyWords");
                _KeyWords = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KeyWords");
                OnKeyWordsChanged();
            }
        }
        private global::System.String _KeyWords;
        partial void OnKeyWordsChanging(global::System.String value);
        partial void OnKeyWordsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductImage
        {
            get
            {
                return _ProductImage;
            }
            set
            {
                OnProductImageChanging(value);
                ReportPropertyChanging("ProductImage");
                _ProductImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductImage");
                OnProductImageChanged();
            }
        }
        private global::System.String _ProductImage;
        partial void OnProductImageChanging(global::System.String value);
        partial void OnProductImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal UnitCost
        {
            get
            {
                return _UnitCost;
            }
            set
            {
                OnUnitCostChanging(value);
                ReportPropertyChanging("UnitCost");
                _UnitCost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitCost");
                OnUnitCostChanged();
            }
        }
        private global::System.Decimal _UnitCost;
        partial void OnUnitCostChanging(global::System.Decimal value);
        partial void OnUnitCostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> UnitCost2
        {
            get
            {
                return _UnitCost2;
            }
            set
            {
                OnUnitCost2Changing(value);
                ReportPropertyChanging("UnitCost2");
                _UnitCost2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitCost2");
                OnUnitCost2Changed();
            }
        }
        private Nullable<global::System.Decimal> _UnitCost2;
        partial void OnUnitCost2Changing(Nullable<global::System.Decimal> value);
        partial void OnUnitCost2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> UnitCost3
        {
            get
            {
                return _UnitCost3;
            }
            set
            {
                OnUnitCost3Changing(value);
                ReportPropertyChanging("UnitCost3");
                _UnitCost3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitCost3");
                OnUnitCost3Changed();
            }
        }
        private Nullable<global::System.Decimal> _UnitCost3;
        partial void OnUnitCost3Changing(Nullable<global::System.Decimal> value);
        partial void OnUnitCost3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> UnitCost4
        {
            get
            {
                return _UnitCost4;
            }
            set
            {
                OnUnitCost4Changing(value);
                ReportPropertyChanging("UnitCost4");
                _UnitCost4 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitCost4");
                OnUnitCost4Changed();
            }
        }
        private Nullable<global::System.Decimal> _UnitCost4;
        partial void OnUnitCost4Changing(Nullable<global::System.Decimal> value);
        partial void OnUnitCost4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> UnitCost5
        {
            get
            {
                return _UnitCost5;
            }
            set
            {
                OnUnitCost5Changing(value);
                ReportPropertyChanging("UnitCost5");
                _UnitCost5 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitCost5");
                OnUnitCost5Changed();
            }
        }
        private Nullable<global::System.Decimal> _UnitCost5;
        partial void OnUnitCost5Changing(Nullable<global::System.Decimal> value);
        partial void OnUnitCost5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> UnitCost6
        {
            get
            {
                return _UnitCost6;
            }
            set
            {
                OnUnitCost6Changing(value);
                ReportPropertyChanging("UnitCost6");
                _UnitCost6 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitCost6");
                OnUnitCost6Changed();
            }
        }
        private Nullable<global::System.Decimal> _UnitCost6;
        partial void OnUnitCost6Changing(Nullable<global::System.Decimal> value);
        partial void OnUnitCost6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DescriptionHTML
        {
            get
            {
                return _DescriptionHTML;
            }
            set
            {
                OnDescriptionHTMLChanging(value);
                ReportPropertyChanging("DescriptionHTML");
                _DescriptionHTML = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DescriptionHTML");
                OnDescriptionHTMLChanged();
            }
        }
        private global::System.String _DescriptionHTML;
        partial void OnDescriptionHTMLChanging(global::System.String value);
        partial void OnDescriptionHTMLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                OnURLChanging(value);
                ReportPropertyChanging("URL");
                _URL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("URL");
                OnURLChanged();
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Stock
        {
            get
            {
                return _Stock;
            }
            set
            {
                OnStockChanging(value);
                ReportPropertyChanging("Stock");
                _Stock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Stock");
                OnStockChanged();
            }
        }
        private Nullable<global::System.Int32> _Stock;
        partial void OnStockChanging(Nullable<global::System.Int32> value);
        partial void OnStockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OrderQuant
        {
            get
            {
                return _OrderQuant;
            }
            set
            {
                OnOrderQuantChanging(value);
                ReportPropertyChanging("OrderQuant");
                _OrderQuant = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OrderQuant");
                OnOrderQuantChanged();
            }
        }
        private global::System.String _OrderQuant;
        partial void OnOrderQuantChanging(global::System.String value);
        partial void OnOrderQuantChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                OnWeightChanging(value);
                ReportPropertyChanging("Weight");
                _Weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Weight");
                OnWeightChanged();
            }
        }
        private Nullable<global::System.Decimal> _Weight;
        partial void OnWeightChanging(Nullable<global::System.Decimal> value);
        partial void OnWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Volume
        {
            get
            {
                return _Volume;
            }
            set
            {
                OnVolumeChanging(value);
                ReportPropertyChanging("Volume");
                _Volume = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Volume");
                OnVolumeChanged();
            }
        }
        private Nullable<global::System.Decimal> _Volume;
        partial void OnVolumeChanging(Nullable<global::System.Decimal> value);
        partial void OnVolumeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Length
        {
            get
            {
                return _Length;
            }
            set
            {
                OnLengthChanging(value);
                ReportPropertyChanging("Length");
                _Length = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Length");
                OnLengthChanged();
            }
        }
        private Nullable<global::System.Decimal> _Length;
        partial void OnLengthChanging(Nullable<global::System.Decimal> value);
        partial void OnLengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Width
        {
            get
            {
                return _Width;
            }
            set
            {
                OnWidthChanging(value);
                ReportPropertyChanging("Width");
                _Width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Width");
                OnWidthChanged();
            }
        }
        private Nullable<global::System.Decimal> _Width;
        partial void OnWidthChanging(Nullable<global::System.Decimal> value);
        partial void OnWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private Nullable<global::System.Decimal> _Height;
        partial void OnHeightChanging(Nullable<global::System.Decimal> value);
        partial void OnHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> FreightCosts1
        {
            get
            {
                return _FreightCosts1;
            }
            set
            {
                OnFreightCosts1Changing(value);
                ReportPropertyChanging("FreightCosts1");
                _FreightCosts1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FreightCosts1");
                OnFreightCosts1Changed();
            }
        }
        private Nullable<global::System.Decimal> _FreightCosts1;
        partial void OnFreightCosts1Changing(Nullable<global::System.Decimal> value);
        partial void OnFreightCosts1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> FreightCosts2
        {
            get
            {
                return _FreightCosts2;
            }
            set
            {
                OnFreightCosts2Changing(value);
                ReportPropertyChanging("FreightCosts2");
                _FreightCosts2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FreightCosts2");
                OnFreightCosts2Changed();
            }
        }
        private Nullable<global::System.Decimal> _FreightCosts2;
        partial void OnFreightCosts2Changing(Nullable<global::System.Decimal> value);
        partial void OnFreightCosts2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Featured
        {
            get
            {
                return _Featured;
            }
            set
            {
                OnFeaturedChanging(value);
                ReportPropertyChanging("Featured");
                _Featured = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Featured");
                OnFeaturedChanged();
            }
        }
        private global::System.Boolean _Featured;
        partial void OnFeaturedChanging(global::System.Boolean value);
        partial void OnFeaturedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal SalePrice
        {
            get
            {
                return _SalePrice;
            }
            set
            {
                OnSalePriceChanging(value);
                ReportPropertyChanging("SalePrice");
                _SalePrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SalePrice");
                OnSalePriceChanged();
            }
        }
        private global::System.Decimal _SalePrice;
        partial void OnSalePriceChanging(global::System.Decimal value);
        partial void OnSalePriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SaleStart
        {
            get
            {
                return _SaleStart;
            }
            set
            {
                OnSaleStartChanging(value);
                ReportPropertyChanging("SaleStart");
                _SaleStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SaleStart");
                OnSaleStartChanged();
            }
        }
        private Nullable<global::System.DateTime> _SaleStart;
        partial void OnSaleStartChanging(Nullable<global::System.DateTime> value);
        partial void OnSaleStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SaleEnd
        {
            get
            {
                return _SaleEnd;
            }
            set
            {
                OnSaleEndChanging(value);
                ReportPropertyChanging("SaleEnd");
                _SaleEnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SaleEnd");
                OnSaleEndChanged();
            }
        }
        private Nullable<global::System.DateTime> _SaleEnd;
        partial void OnSaleEndChanging(Nullable<global::System.DateTime> value);
        partial void OnSaleEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> DownLoad
        {
            get
            {
                return _DownLoad;
            }
            set
            {
                OnDownLoadChanging(value);
                ReportPropertyChanging("DownLoad");
                _DownLoad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DownLoad");
                OnDownLoadChanged();
            }
        }
        private Nullable<global::System.Boolean> _DownLoad;
        partial void OnDownLoadChanging(Nullable<global::System.Boolean> value);
        partial void OnDownLoadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZIPPassWord
        {
            get
            {
                return _ZIPPassWord;
            }
            set
            {
                OnZIPPassWordChanging(value);
                ReportPropertyChanging("ZIPPassWord");
                _ZIPPassWord = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZIPPassWord");
                OnZIPPassWordChanged();
            }
        }
        private global::System.String _ZIPPassWord;
        partial void OnZIPPassWordChanging(global::System.String value);
        partial void OnZIPPassWordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DownLoadFile
        {
            get
            {
                return _DownLoadFile;
            }
            set
            {
                OnDownLoadFileChanging(value);
                ReportPropertyChanging("DownLoadFile");
                _DownLoadFile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DownLoadFile");
                OnDownLoadFileChanged();
            }
        }
        private global::System.String _DownLoadFile;
        partial void OnDownLoadFileChanging(global::System.String value);
        partial void OnDownLoadFileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Archive
        {
            get
            {
                return _Archive;
            }
            set
            {
                OnArchiveChanging(value);
                ReportPropertyChanging("Archive");
                _Archive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Archive");
                OnArchiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _Archive;
        partial void OnArchiveChanging(Nullable<global::System.Boolean> value);
        partial void OnArchiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CreatedByUser
        {
            get
            {
                return _CreatedByUser;
            }
            set
            {
                OnCreatedByUserChanging(value);
                ReportPropertyChanging("CreatedByUser");
                _CreatedByUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedByUser");
                OnCreatedByUserChanged();
            }
        }
        private global::System.Int32 _CreatedByUser;
        partial void OnCreatedByUserChanging(global::System.Int32 value);
        partial void OnCreatedByUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BulkPriceLimit1
        {
            get
            {
                return _BulkPriceLimit1;
            }
            set
            {
                OnBulkPriceLimit1Changing(value);
                ReportPropertyChanging("BulkPriceLimit1");
                _BulkPriceLimit1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BulkPriceLimit1");
                OnBulkPriceLimit1Changed();
            }
        }
        private global::System.Int32 _BulkPriceLimit1;
        partial void OnBulkPriceLimit1Changing(global::System.Int32 value);
        partial void OnBulkPriceLimit1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BulkPriceLimit2
        {
            get
            {
                return _BulkPriceLimit2;
            }
            set
            {
                OnBulkPriceLimit2Changing(value);
                ReportPropertyChanging("BulkPriceLimit2");
                _BulkPriceLimit2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BulkPriceLimit2");
                OnBulkPriceLimit2Changed();
            }
        }
        private global::System.Int32 _BulkPriceLimit2;
        partial void OnBulkPriceLimit2Changing(global::System.Int32 value);
        partial void OnBulkPriceLimit2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BulkPriceLimit3
        {
            get
            {
                return _BulkPriceLimit3;
            }
            set
            {
                OnBulkPriceLimit3Changing(value);
                ReportPropertyChanging("BulkPriceLimit3");
                _BulkPriceLimit3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BulkPriceLimit3");
                OnBulkPriceLimit3Changed();
            }
        }
        private global::System.Int32 _BulkPriceLimit3;
        partial void OnBulkPriceLimit3Changing(global::System.Int32 value);
        partial void OnBulkPriceLimit3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BulkPriceLimit4
        {
            get
            {
                return _BulkPriceLimit4;
            }
            set
            {
                OnBulkPriceLimit4Changing(value);
                ReportPropertyChanging("BulkPriceLimit4");
                _BulkPriceLimit4 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BulkPriceLimit4");
                OnBulkPriceLimit4Changed();
            }
        }
        private global::System.Int32 _BulkPriceLimit4;
        partial void OnBulkPriceLimit4Changing(global::System.Int32 value);
        partial void OnBulkPriceLimit4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BulkPriceLimit5
        {
            get
            {
                return _BulkPriceLimit5;
            }
            set
            {
                OnBulkPriceLimit5Changing(value);
                ReportPropertyChanging("BulkPriceLimit5");
                _BulkPriceLimit5 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BulkPriceLimit5");
                OnBulkPriceLimit5Changed();
            }
        }
        private global::System.Int32 _BulkPriceLimit5;
        partial void OnBulkPriceLimit5Changing(global::System.Int32 value);
        partial void OnBulkPriceLimit5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCreated;
        partial void OnDateCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RoleID
        {
            get
            {
                return _RoleID;
            }
            set
            {
                OnRoleIDChanging(value);
                ReportPropertyChanging("RoleID");
                _RoleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleID");
                OnRoleIDChanged();
            }
        }
        private Nullable<global::System.Int32> _RoleID;
        partial void OnRoleIDChanging(Nullable<global::System.Int32> value);
        partial void OnRoleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SubscriptionPeriod
        {
            get
            {
                return _SubscriptionPeriod;
            }
            set
            {
                OnSubscriptionPeriodChanging(value);
                ReportPropertyChanging("SubscriptionPeriod");
                _SubscriptionPeriod = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SubscriptionPeriod");
                OnSubscriptionPeriodChanged();
            }
        }
        private Nullable<global::System.Int32> _SubscriptionPeriod;
        partial void OnSubscriptionPeriodChanging(Nullable<global::System.Int32> value);
        partial void OnSubscriptionPeriodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> RecurringBilling
        {
            get
            {
                return _RecurringBilling;
            }
            set
            {
                OnRecurringBillingChanging(value);
                ReportPropertyChanging("RecurringBilling");
                _RecurringBilling = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecurringBilling");
                OnRecurringBillingChanged();
            }
        }
        private Nullable<global::System.Boolean> _RecurringBilling;
        partial void OnRecurringBillingChanging(Nullable<global::System.Boolean> value);
        partial void OnRecurringBillingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> TaxExempt
        {
            get
            {
                return _TaxExempt;
            }
            set
            {
                OnTaxExemptChanging(value);
                ReportPropertyChanging("TaxExempt");
                _TaxExempt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TaxExempt");
                OnTaxExemptChanged();
            }
        }
        private Nullable<global::System.Boolean> _TaxExempt;
        partial void OnTaxExemptChanging(Nullable<global::System.Boolean> value);
        partial void OnTaxExemptChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ShipExempt
        {
            get
            {
                return _ShipExempt;
            }
            set
            {
                OnShipExemptChanging(value);
                ReportPropertyChanging("ShipExempt");
                _ShipExempt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShipExempt");
                OnShipExemptChanged();
            }
        }
        private Nullable<global::System.Boolean> _ShipExempt;
        partial void OnShipExemptChanging(Nullable<global::System.Boolean> value);
        partial void OnShipExemptChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal InsuredValue
        {
            get
            {
                return _InsuredValue;
            }
            set
            {
                OnInsuredValueChanging(value);
                ReportPropertyChanging("InsuredValue");
                _InsuredValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InsuredValue");
                OnInsuredValueChanged();
            }
        }
        private global::System.Decimal _InsuredValue;
        partial void OnInsuredValueChanging(global::System.Decimal value);
        partial void OnInsuredValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PublicationStart
        {
            get
            {
                return _PublicationStart;
            }
            set
            {
                OnPublicationStartChanging(value);
                ReportPropertyChanging("PublicationStart");
                _PublicationStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PublicationStart");
                OnPublicationStartChanged();
            }
        }
        private Nullable<global::System.DateTime> _PublicationStart;
        partial void OnPublicationStartChanging(Nullable<global::System.DateTime> value);
        partial void OnPublicationStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PublicationEnd
        {
            get
            {
                return _PublicationEnd;
            }
            set
            {
                OnPublicationEndChanging(value);
                ReportPropertyChanging("PublicationEnd");
                _PublicationEnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PublicationEnd");
                OnPublicationEndChanged();
            }
        }
        private Nullable<global::System.DateTime> _PublicationEnd;
        partial void OnPublicationEndChanging(Nullable<global::System.DateTime> value);
        partial void OnPublicationEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean DonationItem
        {
            get
            {
                return _DonationItem;
            }
            set
            {
                OnDonationItemChanging(value);
                ReportPropertyChanging("DonationItem");
                _DonationItem = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DonationItem");
                OnDonationItemChanged();
            }
        }
        private global::System.Boolean _DonationItem;
        partial void OnDonationItemChanging(global::System.Boolean value);
        partial void OnDonationItemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PayPalSubscription
        {
            get
            {
                return _PayPalSubscription;
            }
            set
            {
                OnPayPalSubscriptionChanging(value);
                ReportPropertyChanging("PayPalSubscription");
                _PayPalSubscription = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PayPalSubscription");
                OnPayPalSubscriptionChanged();
            }
        }
        private global::System.Boolean _PayPalSubscription;
        partial void OnPayPalSubscriptionChanging(global::System.Boolean value);
        partial void OnPayPalSubscriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean UseRoleFees
        {
            get
            {
                return _UseRoleFees;
            }
            set
            {
                OnUseRoleFeesChanging(value);
                ReportPropertyChanging("UseRoleFees");
                _UseRoleFees = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UseRoleFees");
                OnUseRoleFeesChanged();
            }
        }
        private global::System.Boolean _UseRoleFees;
        partial void OnUseRoleFeesChanging(global::System.Boolean value);
        partial void OnUseRoleFeesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ProductCost
        {
            get
            {
                return _ProductCost;
            }
            set
            {
                OnProductCostChanging(value);
                ReportPropertyChanging("ProductCost");
                _ProductCost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductCost");
                OnProductCostChanged();
            }
        }
        private global::System.Decimal _ProductCost;
        partial void OnProductCostChanging(global::System.Decimal value);
        partial void OnProductCostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RoleExpiryType
        {
            get
            {
                return _RoleExpiryType;
            }
            set
            {
                OnRoleExpiryTypeChanging(value);
                ReportPropertyChanging("RoleExpiryType");
                _RoleExpiryType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RoleExpiryType");
                OnRoleExpiryTypeChanged();
            }
        }
        private global::System.String _RoleExpiryType;
        partial void OnRoleExpiryTypeChanging(global::System.String value);
        partial void OnRoleExpiryTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ItemDeliveryType
        {
            get
            {
                return _ItemDeliveryType;
            }
            set
            {
                OnItemDeliveryTypeChanging(value);
                ReportPropertyChanging("ItemDeliveryType");
                _ItemDeliveryType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ItemDeliveryType");
                OnItemDeliveryTypeChanged();
            }
        }
        private global::System.String _ItemDeliveryType;
        partial void OnItemDeliveryTypeChanging(global::System.String value);
        partial void OnItemDeliveryTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReorderPoint
        {
            get
            {
                return _ReorderPoint;
            }
            set
            {
                OnReorderPointChanging(value);
                ReportPropertyChanging("ReorderPoint");
                _ReorderPoint = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReorderPoint");
                OnReorderPointChanged();
            }
        }
        private global::System.Int32 _ReorderPoint;
        partial void OnReorderPointChanging(global::System.Int32 value);
        partial void OnReorderPointChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OrderQuantValidExpr
        {
            get
            {
                return _OrderQuantValidExpr;
            }
            set
            {
                OnOrderQuantValidExprChanging(value);
                ReportPropertyChanging("OrderQuantValidExpr");
                _OrderQuantValidExpr = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OrderQuantValidExpr");
                OnOrderQuantValidExprChanged();
            }
        }
        private global::System.String _OrderQuantValidExpr;
        partial void OnOrderQuantValidExprChanging(global::System.String value);
        partial void OnOrderQuantValidExprChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ShippingAddress
        {
            get
            {
                return _ShippingAddress;
            }
            set
            {
                OnShippingAddressChanging(value);
                ReportPropertyChanging("ShippingAddress");
                _ShippingAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ShippingAddress");
                OnShippingAddressChanged();
            }
        }
        private global::System.String _ShippingAddress;
        partial void OnShippingAddressChanging(global::System.String value);
        partial void OnShippingAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OrigProductID
        {
            get
            {
                return _OrigProductID;
            }
            set
            {
                OnOrigProductIDChanging(value);
                ReportPropertyChanging("OrigProductID");
                _OrigProductID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrigProductID");
                OnOrigProductIDChanged();
            }
        }
        private Nullable<global::System.Int32> _OrigProductID;
        partial void OnOrigProductIDChanging(Nullable<global::System.Int32> value);
        partial void OnOrigProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean AuctionFinished
        {
            get
            {
                return _AuctionFinished;
            }
            set
            {
                OnAuctionFinishedChanging(value);
                ReportPropertyChanging("AuctionFinished");
                _AuctionFinished = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuctionFinished");
                OnAuctionFinishedChanged();
            }
        }
        private global::System.Boolean _AuctionFinished;
        partial void OnAuctionFinishedChanging(global::System.Boolean value);
        partial void OnAuctionFinishedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> StartingPrice
        {
            get
            {
                return _StartingPrice;
            }
            set
            {
                OnStartingPriceChanging(value);
                ReportPropertyChanging("StartingPrice");
                _StartingPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartingPrice");
                OnStartingPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _StartingPrice;
        partial void OnStartingPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnStartingPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ReservePrice
        {
            get
            {
                return _ReservePrice;
            }
            set
            {
                OnReservePriceChanging(value);
                ReportPropertyChanging("ReservePrice");
                _ReservePrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReservePrice");
                OnReservePriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _ReservePrice;
        partial void OnReservePriceChanging(Nullable<global::System.Decimal> value);
        partial void OnReservePriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LastModifiedByUserID
        {
            get
            {
                return _LastModifiedByUserID;
            }
            set
            {
                OnLastModifiedByUserIDChanging(value);
                ReportPropertyChanging("LastModifiedByUserID");
                _LastModifiedByUserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedByUserID");
                OnLastModifiedByUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _LastModifiedByUserID;
        partial void OnLastModifiedByUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnLastModifiedByUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastModifiedOnDate
        {
            get
            {
                return _LastModifiedOnDate;
            }
            set
            {
                OnLastModifiedOnDateChanging(value);
                ReportPropertyChanging("LastModifiedOnDate");
                _LastModifiedOnDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedOnDate");
                OnLastModifiedOnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastModifiedOnDate;
        partial void OnLastModifiedOnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastModifiedOnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TaxCode
        {
            get
            {
                return _TaxCode;
            }
            set
            {
                OnTaxCodeChanging(value);
                ReportPropertyChanging("TaxCode");
                _TaxCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TaxCode");
                OnTaxCodeChanged();
            }
        }
        private global::System.String _TaxCode;
        partial void OnTaxCodeChanging(global::System.String value);
        partial void OnTaxCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MaxWeight
        {
            get
            {
                return _MaxWeight;
            }
            set
            {
                OnMaxWeightChanging(value);
                ReportPropertyChanging("MaxWeight");
                _MaxWeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxWeight");
                OnMaxWeightChanged();
            }
        }
        private Nullable<global::System.Decimal> _MaxWeight;
        partial void OnMaxWeightChanging(Nullable<global::System.Decimal> value);
        partial void OnMaxWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TotalPeriods
        {
            get
            {
                return _TotalPeriods;
            }
            set
            {
                OnTotalPeriodsChanging(value);
                ReportPropertyChanging("TotalPeriods");
                _TotalPeriods = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalPeriods");
                OnTotalPeriodsChanged();
            }
        }
        private Nullable<global::System.Int32> _TotalPeriods;
        partial void OnTotalPeriodsChanging(Nullable<global::System.Int32> value);
        partial void OnTotalPeriodsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> NonStockItem
        {
            get
            {
                return _NonStockItem;
            }
            set
            {
                OnNonStockItemChanging(value);
                ReportPropertyChanging("NonStockItem");
                _NonStockItem = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NonStockItem");
                OnNonStockItemChanged();
            }
        }
        private Nullable<global::System.Boolean> _NonStockItem;
        partial void OnNonStockItemChanging(Nullable<global::System.Boolean> value);
        partial void OnNonStockItemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StockedColorID
        {
            get
            {
                return _StockedColorID;
            }
            set
            {
                OnStockedColorIDChanging(value);
                ReportPropertyChanging("StockedColorID");
                _StockedColorID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StockedColorID");
                OnStockedColorIDChanged();
            }
        }
        private Nullable<global::System.Int32> _StockedColorID;
        partial void OnStockedColorIDChanging(Nullable<global::System.Int32> value);
        partial void OnStockedColorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StockedColorID2
        {
            get
            {
                return _StockedColorID2;
            }
            set
            {
                OnStockedColorID2Changing(value);
                ReportPropertyChanging("StockedColorID2");
                _StockedColorID2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StockedColorID2");
                OnStockedColorID2Changed();
            }
        }
        private Nullable<global::System.Int32> _StockedColorID2;
        partial void OnStockedColorID2Changing(Nullable<global::System.Int32> value);
        partial void OnStockedColorID2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StockedColorID3
        {
            get
            {
                return _StockedColorID3;
            }
            set
            {
                OnStockedColorID3Changing(value);
                ReportPropertyChanging("StockedColorID3");
                _StockedColorID3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StockedColorID3");
                OnStockedColorID3Changed();
            }
        }
        private Nullable<global::System.Int32> _StockedColorID3;
        partial void OnStockedColorID3Changing(Nullable<global::System.Int32> value);
        partial void OnStockedColorID3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StockedColorID4
        {
            get
            {
                return _StockedColorID4;
            }
            set
            {
                OnStockedColorID4Changing(value);
                ReportPropertyChanging("StockedColorID4");
                _StockedColorID4 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StockedColorID4");
                OnStockedColorID4Changed();
            }
        }
        private Nullable<global::System.Int32> _StockedColorID4;
        partial void OnStockedColorID4Changing(Nullable<global::System.Int32> value);
        partial void OnStockedColorID4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StockedColorID5
        {
            get
            {
                return _StockedColorID5;
            }
            set
            {
                OnStockedColorID5Changing(value);
                ReportPropertyChanging("StockedColorID5");
                _StockedColorID5 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StockedColorID5");
                OnStockedColorID5Changed();
            }
        }
        private Nullable<global::System.Int32> _StockedColorID5;
        partial void OnStockedColorID5Changing(Nullable<global::System.Int32> value);
        partial void OnStockedColorID5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StockedColorID6
        {
            get
            {
                return _StockedColorID6;
            }
            set
            {
                OnStockedColorID6Changing(value);
                ReportPropertyChanging("StockedColorID6");
                _StockedColorID6 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StockedColorID6");
                OnStockedColorID6Changed();
            }
        }
        private Nullable<global::System.Int32> _StockedColorID6;
        partial void OnStockedColorID6Changing(Nullable<global::System.Int32> value);
        partial void OnStockedColorID6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DealerTier1Price
        {
            get
            {
                return _DealerTier1Price;
            }
            set
            {
                OnDealerTier1PriceChanging(value);
                ReportPropertyChanging("DealerTier1Price");
                _DealerTier1Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DealerTier1Price");
                OnDealerTier1PriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _DealerTier1Price;
        partial void OnDealerTier1PriceChanging(Nullable<global::System.Decimal> value);
        partial void OnDealerTier1PriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DealerTier2Price
        {
            get
            {
                return _DealerTier2Price;
            }
            set
            {
                OnDealerTier2PriceChanging(value);
                ReportPropertyChanging("DealerTier2Price");
                _DealerTier2Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DealerTier2Price");
                OnDealerTier2PriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _DealerTier2Price;
        partial void OnDealerTier2PriceChanging(Nullable<global::System.Decimal> value);
        partial void OnDealerTier2PriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DealerTier3Price
        {
            get
            {
                return _DealerTier3Price;
            }
            set
            {
                OnDealerTier3PriceChanging(value);
                ReportPropertyChanging("DealerTier3Price");
                _DealerTier3Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DealerTier3Price");
                OnDealerTier3PriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _DealerTier3Price;
        partial void OnDealerTier3PriceChanging(Nullable<global::System.Decimal> value);
        partial void OnDealerTier3PriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DealerTier4Price
        {
            get
            {
                return _DealerTier4Price;
            }
            set
            {
                OnDealerTier4PriceChanging(value);
                ReportPropertyChanging("DealerTier4Price");
                _DealerTier4Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DealerTier4Price");
                OnDealerTier4PriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _DealerTier4Price;
        partial void OnDealerTier4PriceChanging(Nullable<global::System.Decimal> value);
        partial void OnDealerTier4PriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ConsumerTier1Price
        {
            get
            {
                return _ConsumerTier1Price;
            }
            set
            {
                OnConsumerTier1PriceChanging(value);
                ReportPropertyChanging("ConsumerTier1Price");
                _ConsumerTier1Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConsumerTier1Price");
                OnConsumerTier1PriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _ConsumerTier1Price;
        partial void OnConsumerTier1PriceChanging(Nullable<global::System.Decimal> value);
        partial void OnConsumerTier1PriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ConsumerTier2Price
        {
            get
            {
                return _ConsumerTier2Price;
            }
            set
            {
                OnConsumerTier2PriceChanging(value);
                ReportPropertyChanging("ConsumerTier2Price");
                _ConsumerTier2Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConsumerTier2Price");
                OnConsumerTier2PriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _ConsumerTier2Price;
        partial void OnConsumerTier2PriceChanging(Nullable<global::System.Decimal> value);
        partial void OnConsumerTier2PriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ConsumerTier3Price
        {
            get
            {
                return _ConsumerTier3Price;
            }
            set
            {
                OnConsumerTier3PriceChanging(value);
                ReportPropertyChanging("ConsumerTier3Price");
                _ConsumerTier3Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConsumerTier3Price");
                OnConsumerTier3PriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _ConsumerTier3Price;
        partial void OnConsumerTier3PriceChanging(Nullable<global::System.Decimal> value);
        partial void OnConsumerTier3PriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ConsumerTier4Price
        {
            get
            {
                return _ConsumerTier4Price;
            }
            set
            {
                OnConsumerTier4PriceChanging(value);
                ReportPropertyChanging("ConsumerTier4Price");
                _ConsumerTier4Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConsumerTier4Price");
                OnConsumerTier4PriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _ConsumerTier4Price;
        partial void OnConsumerTier4PriceChanging(Nullable<global::System.Decimal> value);
        partial void OnConsumerTier4PriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiscountClass
        {
            get
            {
                return _DiscountClass;
            }
            set
            {
                OnDiscountClassChanging(value);
                ReportPropertyChanging("DiscountClass");
                _DiscountClass = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DiscountClass");
                OnDiscountClassChanged();
            }
        }
        private global::System.String _DiscountClass;
        partial void OnDiscountClassChanging(global::System.String value);
        partial void OnDiscountClassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DiscountClassID
        {
            get
            {
                return _DiscountClassID;
            }
            set
            {
                OnDiscountClassIDChanging(value);
                ReportPropertyChanging("DiscountClassID");
                _DiscountClassID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DiscountClassID");
                OnDiscountClassIDChanged();
            }
        }
        private Nullable<global::System.Int32> _DiscountClassID;
        partial void OnDiscountClassIDChanging(Nullable<global::System.Int32> value);
        partial void OnDiscountClassIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CMSProductID
        {
            get
            {
                return _CMSProductID;
            }
            set
            {
                OnCMSProductIDChanging(value);
                ReportPropertyChanging("CMSProductID");
                _CMSProductID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CMSProductID");
                OnCMSProductIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CMSProductID;
        partial void OnCMSProductIDChanging(Nullable<global::System.Int32> value);
        partial void OnCMSProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TAASportID
        {
            get
            {
                return _TAASportID;
            }
            set
            {
                OnTAASportIDChanging(value);
                ReportPropertyChanging("TAASportID");
                _TAASportID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TAASportID");
                OnTAASportIDChanged();
            }
        }
        private Nullable<global::System.Int32> _TAASportID;
        partial void OnTAASportIDChanging(Nullable<global::System.Int32> value);
        partial void OnTAASportIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CMSProductDesign
        {
            get
            {
                return _CMSProductDesign;
            }
            set
            {
                OnCMSProductDesignChanging(value);
                ReportPropertyChanging("CMSProductDesign");
                _CMSProductDesign = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CMSProductDesign");
                OnCMSProductDesignChanged();
            }
        }
        private global::System.String _CMSProductDesign;
        partial void OnCMSProductDesignChanging(global::System.String value);
        partial void OnCMSProductDesignChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SortOrder
        {
            get
            {
                return _SortOrder;
            }
            set
            {
                OnSortOrderChanging(value);
                ReportPropertyChanging("SortOrder");
                _SortOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SortOrder");
                OnSortOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _SortOrder;
        partial void OnSortOrderChanging(Nullable<global::System.Int32> value);
        partial void OnSortOrderChanged();

        #endregion
    
    }

    #endregion
    
}
